import type { MissionSummary } from '../../types';

// Auto-generated by scripts/generate-mission-summaries.ts
export const MISSION_SUMMARIES_Y10: MissionSummary[] = [
  {
    "id": 1011,
    "grade": 10,
    "unitId": 1,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 1: 火攻轨迹与二次函数",
      "en": "Unit 1: Fire Attack & Quadratic Functions"
    },
    "title": {
      "zh": "草船借箭",
      "en": "Straw Boats Borrow Arrows"
    },
    "topic": "Functions",
    "kpId": "kp-2.10-01"
  },
  {
    "id": 1012,
    "grade": 10,
    "unitId": 1,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 1: 火攻轨迹与二次函数",
      "en": "Unit 1: Fire Attack & Quadratic Functions"
    },
    "title": {
      "zh": "火烧赤壁",
      "en": "Burning Red Cliffs"
    },
    "topic": "Functions",
    "kpId": "kp-2.10-01"
  },
  {
    "id": 1013,
    "grade": 10,
    "unitId": 1,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 1: 火攻轨迹与二次函数",
      "en": "Unit 1: Fire Attack & Quadratic Functions"
    },
    "title": {
      "zh": "投石射程",
      "en": "Catapult Range"
    },
    "topic": "Functions",
    "kpId": "kp-2.10-01"
  },
  {
    "id": 1021,
    "grade": 10,
    "unitId": 2,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 2: 连环计与联立方程",
      "en": "Unit 2: Chain Strategy & Simultaneous Equations"
    },
    "title": {
      "zh": "兵力合围",
      "en": "Troop Encirclement"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-01"
  },
  {
    "id": 1022,
    "grade": 10,
    "unitId": 2,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 2: 连环计与联立方程",
      "en": "Unit 2: Chain Strategy & Simultaneous Equations"
    },
    "title": {
      "zh": "粮草互换",
      "en": "Resource Exchange"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-01"
  },
  {
    "id": 1023,
    "grade": 10,
    "unitId": 2,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 2: 连环计与联立方程",
      "en": "Unit 2: Chain Strategy & Simultaneous Equations"
    },
    "title": {
      "zh": "战船调度",
      "en": "Ship Deployment"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-01"
  },
  {
    "id": 1031,
    "grade": 10,
    "unitId": 3,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 3: 天命占卜与概率",
      "en": "Unit 3: Divination & Probability"
    },
    "title": {
      "zh": "借东风",
      "en": "Borrowing the East Wind"
    },
    "topic": "Algebra",
    "kpId": "kp-8.1-01"
  },
  {
    "id": 1032,
    "grade": 10,
    "unitId": 3,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 3: 天命占卜与概率",
      "en": "Unit 3: Divination & Probability"
    },
    "title": {
      "zh": "连环计",
      "en": "Chain Link Strategy"
    },
    "topic": "Algebra",
    "kpId": "kp-8.3-02"
  },
  {
    "id": 1033,
    "grade": 10,
    "unitId": 3,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 3: 天命占卜与概率",
      "en": "Unit 3: Divination & Probability"
    },
    "title": {
      "zh": "华容道伏兵",
      "en": "Huarong Pass Ambush"
    },
    "topic": "Algebra",
    "kpId": "kp-8.1-02"
  },
  {
    "id": 1034,
    "grade": 10,
    "unitId": 3,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 3: 天命占卜与概率",
      "en": "Unit 3: Divination & Probability"
    },
    "title": {
      "zh": "两卦连占",
      "en": "Double Divination"
    },
    "topic": "Statistics",
    "kpId": "kp-9.2-01"
  },
  {
    "id": 1041,
    "grade": 10,
    "unitId": 4,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 4: 水战风云与三角函数",
      "en": "Unit 4: Naval Warfare & Trigonometry"
    },
    "title": {
      "zh": "战船间距",
      "en": "Ship Distance"
    },
    "topic": "Geometry",
    "kpId": "kp-6.2-01"
  },
  {
    "id": 1042,
    "grade": 10,
    "unitId": 4,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 4: 水战风云与三角函数",
      "en": "Unit 4: Naval Warfare & Trigonometry"
    },
    "title": {
      "zh": "旗舰夹角",
      "en": "Flagship Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-6.2-01"
  },
  {
    "id": 1043,
    "grade": 10,
    "unitId": 4,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 4: 水战风云与三角函数",
      "en": "Unit 4: Naval Warfare & Trigonometry"
    },
    "title": {
      "zh": "火攻仰角",
      "en": "Fire Attack Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-6.2-01"
  },
  {
    "id": 1051,
    "grade": 10,
    "unitId": 5,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 5: 等差军阵与序列",
      "en": "Unit 5: Military Formations & Sequences"
    },
    "title": {
      "zh": "赤壁增兵",
      "en": "Red Cliffs Reinforcements"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1052,
    "grade": 10,
    "unitId": 5,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 5: 等差军阵与序列",
      "en": "Unit 5: Military Formations & Sequences"
    },
    "title": {
      "zh": "连弩齐射",
      "en": "Crossbow Volley"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1053,
    "grade": 10,
    "unitId": 5,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 5: 等差军阵与序列",
      "en": "Unit 5: Military Formations & Sequences"
    },
    "title": {
      "zh": "粮草消耗",
      "en": "Supply Depletion"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1054,
    "grade": 10,
    "unitId": 5,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 5: 等差军阵与序列",
      "en": "Unit 5: Military Formations & Sequences"
    },
    "title": {
      "zh": "军阵通项",
      "en": "Formation nth Term"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1055,
    "grade": 10,
    "unitId": 5,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 5: 等差军阵与序列",
      "en": "Unit 5: Military Formations & Sequences"
    },
    "title": {
      "zh": "兵力预测",
      "en": "Troop Forecast"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1056,
    "grade": 10,
    "unitId": 5,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 5: 等差军阵与序列",
      "en": "Unit 5: Military Formations & Sequences"
    },
    "title": {
      "zh": "瘟疫蔓延",
      "en": "Plague Spread"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1061,
    "grade": 10,
    "unitId": 6,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 6: 荆州丈量·田亩清册",
      "en": "Unit 6: Jingzhou Survey — Land Registry"
    },
    "title": {
      "zh": "田亩丈量",
      "en": "Farmland Survey"
    },
    "topic": "Geometry",
    "kpId": "kp-5.2-01"
  },
  {
    "id": 1062,
    "grade": 10,
    "unitId": 6,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 6: 荆州丈量·田亩清册",
      "en": "Unit 6: Jingzhou Survey — Land Registry"
    },
    "title": {
      "zh": "堤坝截面",
      "en": "Embankment Cross-Section"
    },
    "topic": "Geometry",
    "kpId": "kp-5.2-02"
  },
  {
    "id": 1063,
    "grade": 10,
    "unitId": 6,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 6: 荆州丈量·田亩清册",
      "en": "Unit 6: Jingzhou Survey — Land Registry"
    },
    "title": {
      "zh": "城墙截面",
      "en": "City Wall Cross-Section"
    },
    "topic": "Geometry",
    "kpId": "kp-5.2-03"
  },
  {
    "id": 1064,
    "grade": 10,
    "unitId": 6,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 6: 荆州丈量·田亩清册",
      "en": "Unit 6: Jingzhou Survey — Land Registry"
    },
    "title": {
      "zh": "瞭望塔占地",
      "en": "Watchtower Footprint"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-01"
  },
  {
    "id": 1065,
    "grade": 10,
    "unitId": 6,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 6: 荆州丈量·田亩清册",
      "en": "Unit 6: Jingzhou Survey — Land Registry"
    },
    "title": {
      "zh": "田界测量",
      "en": "Field Boundary Survey"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-02"
  },
  {
    "id": 1066,
    "grade": 10,
    "unitId": 6,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 6: 荆州丈量·田亩清册",
      "en": "Unit 6: Jingzhou Survey — Land Registry"
    },
    "title": {
      "zh": "城楼会师",
      "en": "Tower Rendezvous"
    },
    "topic": "Geometry",
    "kpId": "kp-4.1-02"
  },
  {
    "id": 1067,
    "grade": 10,
    "unitId": 6,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 6: 荆州丈量·田亩清册",
      "en": "Unit 6: Jingzhou Survey — Land Registry"
    },
    "title": {
      "zh": "烽火定位",
      "en": "Beacon Positioning"
    },
    "topic": "Geometry",
    "kpId": "kp-4.1-02"
  },
  {
    "id": 1071,
    "grade": 10,
    "unitId": 7,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 7: 粮仓体积·城防工事",
      "en": "Unit 7: Granary Volume — Fortifications"
    },
    "title": {
      "zh": "粮仓容积",
      "en": "Granary Capacity"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-01"
  },
  {
    "id": 1072,
    "grade": 10,
    "unitId": 7,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 7: 粮仓体积·城防工事",
      "en": "Unit 7: Granary Volume — Fortifications"
    },
    "title": {
      "zh": "水井深度",
      "en": "Well Depth"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-02"
  },
  {
    "id": 1073,
    "grade": 10,
    "unitId": 7,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 7: 粮仓体积·城防工事",
      "en": "Unit 7: Granary Volume — Fortifications"
    },
    "title": {
      "zh": "烽火台",
      "en": "Beacon Tower"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-03"
  },
  {
    "id": 1081,
    "grade": 10,
    "unitId": 8,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 8: 诸葛连弩·函数与百分比",
      "en": "Unit 8: Zhuge Crossbow — Functions & Percentages"
    },
    "title": {
      "zh": "连弩射程",
      "en": "Crossbow Range"
    },
    "topic": "Functions",
    "kpId": "kp-2.13-01"
  },
  {
    "id": 1082,
    "grade": 10,
    "unitId": 8,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 8: 诸葛连弩·函数与百分比",
      "en": "Unit 8: Zhuge Crossbow — Functions & Percentages"
    },
    "title": {
      "zh": "战损评估",
      "en": "Battle Casualties"
    },
    "topic": "Algebra",
    "kpId": "kp-1.13-01"
  },
  {
    "id": 1083,
    "grade": 10,
    "unitId": 8,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 8: 诸葛连弩·函数与百分比",
      "en": "Unit 8: Zhuge Crossbow — Functions & Percentages"
    },
    "title": {
      "zh": "粮仓复利",
      "en": "Grain Compound Growth"
    },
    "topic": "Algebra",
    "kpId": "kp-1.13-03"
  },
  {
    "id": 1091,
    "grade": 10,
    "unitId": 9,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 9: 阵法变换·八卦阵",
      "en": "Unit 9: Formation Transforms — Eight Trigram Array"
    },
    "title": {
      "zh": "沿河反射",
      "en": "River Reflection"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-01"
  },
  {
    "id": 1092,
    "grade": 10,
    "unitId": 9,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 9: 阵法变换·八卦阵",
      "en": "Unit 9: Formation Transforms — Eight Trigram Array"
    },
    "title": {
      "zh": "阵型平移",
      "en": "Formation Translation"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-03"
  },
  {
    "id": 1093,
    "grade": 10,
    "unitId": 9,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 9: 阵法变换·八卦阵",
      "en": "Unit 9: Formation Transforms — Eight Trigram Array"
    },
    "title": {
      "zh": "旋转阵型",
      "en": "Rotate Formation"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-05"
  },
  {
    "id": 1094,
    "grade": 10,
    "unitId": 9,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 9: 阵法变换·八卦阵",
      "en": "Unit 9: Formation Transforms — Eight Trigram Array"
    },
    "title": {
      "zh": "阵型放大",
      "en": "Formation Enlargement"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-07"
  },
  {
    "id": 1101,
    "grade": 10,
    "unitId": 10,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 10: 栈道工程·高级度量",
      "en": "Unit 10: Plank Road Engineering — Advanced Mensuration"
    },
    "title": {
      "zh": "弧形城墙",
      "en": "Curved Wall"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-03"
  },
  {
    "id": 1102,
    "grade": 10,
    "unitId": 10,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 10: 栈道工程·高级度量",
      "en": "Unit 10: Plank Road Engineering — Advanced Mensuration"
    },
    "title": {
      "zh": "烽火覆盖",
      "en": "Beacon Coverage"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-04"
  },
  {
    "id": 1103,
    "grade": 10,
    "unitId": 10,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 10: 栈道工程·高级度量",
      "en": "Unit 10: Plank Road Engineering — Advanced Mensuration"
    },
    "title": {
      "zh": "两阵距离",
      "en": "Camp Distance"
    },
    "topic": "Geometry",
    "kpId": "kp-3.4-02"
  },
  {
    "id": 10111,
    "grade": 10,
    "unitId": 11,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 11: 赤壁运筹·代数篇",
      "en": "Unit 11: Red Cliffs Algebra — Operations"
    },
    "title": {
      "zh": "火攻展开",
      "en": "Fire Strategy Expansion"
    },
    "topic": "Algebra",
    "kpId": "kp-2.3-01"
  },
  {
    "id": 10112,
    "grade": 10,
    "unitId": 11,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 11: 赤壁运筹·代数篇",
      "en": "Unit 11: Red Cliffs Algebra — Operations"
    },
    "title": {
      "zh": "战后整编",
      "en": "Post-battle Regrouping"
    },
    "topic": "Algebra",
    "kpId": "kp-2.3-03"
  },
  {
    "id": 10113,
    "grade": 10,
    "unitId": 11,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 11: 赤壁运筹·代数篇",
      "en": "Unit 11: Red Cliffs Algebra — Operations"
    },
    "title": {
      "zh": "粮草底线",
      "en": "Supply Threshold"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 10121,
    "grade": 10,
    "unitId": 12,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 12: 赤壁水寨·扇形与弧",
      "en": "Unit 12: Red Cliffs Harbor — Sectors & Arcs"
    },
    "title": {
      "zh": "水寨扇面",
      "en": "Harbor Sector"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-03"
  },
  {
    "id": 10122,
    "grade": 10,
    "unitId": 12,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 12: 赤壁水寨·扇形与弧",
      "en": "Unit 12: Red Cliffs Harbor — Sectors & Arcs"
    },
    "title": {
      "zh": "弧长测量",
      "en": "Arc Length Measure"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-04"
  },
  {
    "id": 10131,
    "grade": 10,
    "unitId": 13,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 13: 天下形势·统计分析",
      "en": "Unit 13: State of the Realm — Statistical Analysis"
    },
    "title": {
      "zh": "军力均值",
      "en": "Military Mean"
    },
    "topic": "Statistics",
    "kpId": "kp-9.1-01"
  },
  {
    "id": 10132,
    "grade": 10,
    "unitId": 13,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 13: 天下形势·统计分析",
      "en": "Unit 13: State of the Realm — Statistical Analysis"
    },
    "title": {
      "zh": "极差分析",
      "en": "Range Analysis"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-03"
  },
  {
    "id": 10133,
    "grade": 10,
    "unitId": 13,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 13: 天下形势·统计分析",
      "en": "Unit 13: State of the Realm — Statistical Analysis"
    },
    "title": {
      "zh": "众数决策",
      "en": "Mode Decision"
    },
    "topic": "Statistics",
    "kpId": "kp-9.1-01"
  },
  {
    "id": 10141,
    "grade": 10,
    "unitId": 14,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 14: 赤壁天机·圆周角定理",
      "en": "Unit 14: Red Cliffs Secrets — Circle Theorems"
    },
    "title": {
      "zh": "半圆直角",
      "en": "Semicircle Right Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-01"
  },
  {
    "id": 10142,
    "grade": 10,
    "unitId": 14,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 14: 赤壁天机·圆周角定理",
      "en": "Unit 14: Red Cliffs Secrets — Circle Theorems"
    },
    "title": {
      "zh": "圆心角定理",
      "en": "Central Angle Theorem"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-02"
  },
  {
    "id": 10151,
    "grade": 10,
    "unitId": 15,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 15: 圆定理",
      "en": "Unit 15: Circle Theorems"
    },
    "title": {
      "zh": "半圆之角",
      "en": "Angle in a Semicircle"
    },
    "topic": "Geometry",
    "kpId": "kp-4.7-01"
  },
  {
    "id": 10152,
    "grade": 10,
    "unitId": 15,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 15: 圆定理",
      "en": "Unit 15: Circle Theorems"
    },
    "title": {
      "zh": "同弓形角",
      "en": "Angles in Same Segment"
    },
    "topic": "Geometry",
    "kpId": "kp-4.7-02"
  },
  {
    "id": 10153,
    "grade": 10,
    "unitId": 15,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 15: 圆定理",
      "en": "Unit 15: Circle Theorems"
    },
    "title": {
      "zh": "圆内接四边形",
      "en": "Cyclic Quadrilateral"
    },
    "topic": "Geometry",
    "kpId": "kp-4.7-03"
  },
  {
    "id": 10154,
    "grade": 10,
    "unitId": 15,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 15: 圆定理",
      "en": "Unit 15: Circle Theorems"
    },
    "title": {
      "zh": "切线与半径",
      "en": "Tangent-Radius"
    },
    "topic": "Geometry",
    "kpId": "kp-4.7-04"
  },
  {
    "id": 10155,
    "grade": 10,
    "unitId": 16,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 16: 正反比例",
      "en": "Unit 16: Direct & Inverse Proportion"
    },
    "title": {
      "zh": "反比兵法",
      "en": "Inverse Proportion"
    },
    "topic": "Algebra",
    "kpId": "kp-2.8-01"
  },
  {
    "id": 10156,
    "grade": 10,
    "unitId": 16,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 16: 正反比例",
      "en": "Unit 16: Direct & Inverse Proportion"
    },
    "title": {
      "zh": "正比平方",
      "en": "Direct Proportion with Square"
    },
    "topic": "Algebra",
    "kpId": "kp-2.8-04"
  },
  {
    "id": 10157,
    "grade": 10,
    "unitId": 16,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 16: 正反比例",
      "en": "Unit 16: Direct & Inverse Proportion"
    },
    "title": {
      "zh": "联合变量",
      "en": "Joint Variation"
    },
    "topic": "Algebra",
    "kpId": "kp-2.8-06"
  },
  {
    "id": 10158,
    "grade": 10,
    "unitId": 16,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 16: 正反比例",
      "en": "Unit 16: Direct & Inverse Proportion"
    },
    "title": {
      "zh": "变量图像",
      "en": "Variation Graphs"
    },
    "topic": "Algebra",
    "kpId": "kp-2.8-08"
  },
  {
    "id": 10159,
    "grade": 10,
    "unitId": 17,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 17: 精度范围",
      "en": "Unit 17: Limits of Accuracy"
    },
    "title": {
      "zh": "上界与下界",
      "en": "Upper & Lower Bounds"
    },
    "topic": "Algebra",
    "kpId": "kp-1.10-01"
  },
  {
    "id": 10160,
    "grade": 10,
    "unitId": 17,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 17: 精度范围",
      "en": "Unit 17: Limits of Accuracy"
    },
    "title": {
      "zh": "运算中的界",
      "en": "Bounds in Calculations"
    },
    "topic": "Algebra",
    "kpId": "kp-1.10-03"
  },
  {
    "id": 10161,
    "grade": 10,
    "unitId": 17,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 17: 精度范围",
      "en": "Unit 17: Limits of Accuracy"
    },
    "title": {
      "zh": "最大最小值",
      "en": "Max & Min Values"
    },
    "topic": "Algebra",
    "kpId": "kp-1.10-04"
  },
  {
    "id": 10162,
    "grade": 10,
    "unitId": 18,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 18: 条件概率",
      "en": "Unit 18: Conditional Probability"
    },
    "title": {
      "zh": "不放回抽取",
      "en": "Without Replacement"
    },
    "topic": "Algebra",
    "kpId": "kp-8.4-01"
  },
  {
    "id": 10163,
    "grade": 10,
    "unitId": 18,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 18: 条件概率",
      "en": "Unit 18: Conditional Probability"
    },
    "title": {
      "zh": "列联表概率",
      "en": "Two-Way Table Probability"
    },
    "topic": "Algebra",
    "kpId": "kp-8.4-02"
  },
  {
    "id": 10164,
    "grade": 10,
    "unitId": 19,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 19: 频率直方图",
      "en": "Unit 19: Histograms"
    },
    "title": {
      "zh": "频率密度",
      "en": "Frequency Density"
    },
    "topic": "Statistics",
    "kpId": "kp-9.7-01"
  },
  {
    "id": 10165,
    "grade": 10,
    "unitId": 19,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 19: 频率直方图",
      "en": "Unit 19: Histograms"
    },
    "title": {
      "zh": "读直方图",
      "en": "Read Histogram"
    },
    "topic": "Statistics",
    "kpId": "kp-9.7-02"
  },
  {
    "id": 10171,
    "grade": 10,
    "unitId": 20,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 20: 不等式进阶",
      "en": "Unit 20: Advanced Inequalities"
    },
    "title": {
      "zh": "图解不等式",
      "en": "Graphical Inequalities"
    },
    "topic": "Algebra",
    "kpId": "kp-2.6-02"
  },
  {
    "id": 10172,
    "grade": 10,
    "unitId": 20,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 20: 不等式进阶",
      "en": "Unit 20: Advanced Inequalities"
    },
    "title": {
      "zh": "负数翻转",
      "en": "Negative Flip"
    },
    "topic": "Algebra",
    "kpId": "kp-2.6-03"
  },
  {
    "id": 10173,
    "grade": 10,
    "unitId": 20,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 20: 不等式进阶",
      "en": "Unit 20: Advanced Inequalities"
    },
    "title": {
      "zh": "双重不等式",
      "en": "Double Inequality"
    },
    "topic": "Algebra",
    "kpId": "kp-2.6-04"
  },
  {
    "id": 10174,
    "grade": 10,
    "unitId": 21,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 21: 比例高级",
      "en": "Unit 21: Advanced Proportion"
    },
    "title": {
      "zh": "正比例平方",
      "en": "Direct Square Proportion"
    },
    "topic": "Algebra",
    "kpId": "kp-2.8-03"
  },
  {
    "id": 10175,
    "grade": 10,
    "unitId": 21,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 21: 比例高级",
      "en": "Unit 21: Advanced Proportion"
    },
    "title": {
      "zh": "反比例",
      "en": "Inverse Proportion"
    },
    "topic": "Algebra",
    "kpId": "kp-2.8-05"
  },
  {
    "id": 10176,
    "grade": 10,
    "unitId": 21,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 21: 比例高级",
      "en": "Unit 21: Advanced Proportion"
    },
    "title": {
      "zh": "部分变分",
      "en": "Partial Variation"
    },
    "topic": "Algebra",
    "kpId": "kp-2.8-07"
  },
  {
    "id": 10177,
    "grade": 10,
    "unitId": 22,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 22: 函数图像进阶",
      "en": "Unit 22: Advanced Function Graphs"
    },
    "title": {
      "zh": "对称轴",
      "en": "Axis of Symmetry"
    },
    "topic": "Functions",
    "kpId": "kp-2.10-03"
  },
  {
    "id": 10178,
    "grade": 10,
    "unitId": 22,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 22: 函数图像进阶",
      "en": "Unit 22: Advanced Function Graphs"
    },
    "title": {
      "zh": "立方函数",
      "en": "Cubic Functions"
    },
    "topic": "Functions",
    "kpId": "kp-2.10-04"
  },
  {
    "id": 10179,
    "grade": 10,
    "unitId": 23,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 23: 圆定理补充",
      "en": "Unit 23: Circle Theorems (Extended)"
    },
    "title": {
      "zh": "半圆角定理",
      "en": "Angle in Semicircle"
    },
    "topic": "Geometry",
    "kpId": "kp-4.7-05"
  },
  {
    "id": 10180,
    "grade": 10,
    "unitId": 23,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 23: 圆定理补充",
      "en": "Unit 23: Circle Theorems (Extended)"
    },
    "title": {
      "zh": "弦切角定理",
      "en": "Alternate Segment Theorem"
    },
    "topic": "Geometry",
    "kpId": "kp-4.7-06"
  },
  {
    "id": 10181,
    "grade": 10,
    "unitId": 24,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 24: 圆弧扇形补充",
      "en": "Unit 24: Arcs & Sectors (Extended)"
    },
    "title": {
      "zh": "圆的面积",
      "en": "Circle Area"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-02"
  },
  {
    "id": 10182,
    "grade": 10,
    "unitId": 24,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 24: 圆弧扇形补充",
      "en": "Unit 24: Arcs & Sectors (Extended)"
    },
    "title": {
      "zh": "半圆弧长",
      "en": "Semicircle Arc Length"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-05"
  },
  {
    "id": 10183,
    "grade": 10,
    "unitId": 24,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 24: 圆弧扇形补充",
      "en": "Unit 24: Arcs & Sectors (Extended)"
    },
    "title": {
      "zh": "圆周长",
      "en": "Circumference"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-06"
  },
  {
    "id": 10184,
    "grade": 10,
    "unitId": 25,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 25: 表面积体积进阶",
      "en": "Unit 25: Advanced Surface Area & Volume"
    },
    "title": {
      "zh": "圆锥体积",
      "en": "Cone Volume"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-04"
  },
  {
    "id": 10185,
    "grade": 10,
    "unitId": 25,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 25: 表面积体积进阶",
      "en": "Unit 25: Advanced Surface Area & Volume"
    },
    "title": {
      "zh": "球体体积",
      "en": "Sphere Volume"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-05"
  },
  {
    "id": 10186,
    "grade": 10,
    "unitId": 25,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 25: 表面积体积进阶",
      "en": "Unit 25: Advanced Surface Area & Volume"
    },
    "title": {
      "zh": "球体表面积",
      "en": "Sphere Surface Area"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-06"
  },
  {
    "id": 10187,
    "grade": 10,
    "unitId": 25,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 25: 表面积体积进阶",
      "en": "Unit 25: Advanced Surface Area & Volume"
    },
    "title": {
      "zh": "圆柱表面积",
      "en": "Cylinder Surface Area"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-07"
  },
  {
    "id": 10188,
    "grade": 10,
    "unitId": 26,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 26: 累积频率",
      "en": "Unit 26: Cumulative Frequency"
    },
    "title": {
      "zh": "累积频率中位数",
      "en": "Cumulative Frequency Median"
    },
    "topic": "Statistics",
    "kpId": "kp-9.6-03"
  },
  {
    "id": 10189,
    "grade": 10,
    "unitId": 26,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 26: 累积频率",
      "en": "Unit 26: Cumulative Frequency"
    },
    "title": {
      "zh": "四分位数",
      "en": "Quartiles from CF"
    },
    "topic": "Statistics",
    "kpId": "kp-9.6-04"
  },
  {
    "id": 10190,
    "grade": 10,
    "unitId": 27,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 27: 组合图形",
      "en": "Unit 27: Compound Shapes"
    },
    "title": {
      "zh": "T形面积",
      "en": "T-Shape Area"
    },
    "topic": "Geometry",
    "kpId": "kp-5.5-02"
  },
  {
    "id": 10191,
    "grade": 10,
    "unitId": 28,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 28: 精度补充",
      "en": "Unit 28: Accuracy Extra"
    },
    "title": {
      "zh": "上界侦测",
      "en": "Upper Bound Detection"
    },
    "topic": "Algebra",
    "kpId": "kp-1.10-02"
  },
  {
    "id": 10192,
    "grade": 10,
    "unitId": 28,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 28: 精度补充",
      "en": "Unit 28: Accuracy Extra"
    },
    "title": {
      "zh": "精度极限",
      "en": "Limits of Accuracy"
    },
    "topic": "Algebra",
    "kpId": "kp-1.10-05"
  },
  {
    "id": 10193,
    "grade": 10,
    "unitId": 28,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 28: 精度补充",
      "en": "Unit 28: Accuracy Extra"
    },
    "title": {
      "zh": "散点预判",
      "en": "Scatter Prediction"
    },
    "topic": "Statistics",
    "kpId": "kp-9.5-02"
  }
] as MissionSummary[];
