import type { MissionSummary } from '../../types';

// Auto-generated by scripts/generate-mission-summaries.ts
export const MISSION_SUMMARIES_Y11: MissionSummary[] = [
  {
    "id": 1111,
    "grade": 11,
    "unitId": 1,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 1: 出师表与微分优化",
      "en": "Unit 1: Memorial & Differentiation"
    },
    "title": {
      "zh": "出师北伐",
      "en": "Northern Expedition"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-01"
  },
  {
    "id": 1112,
    "grade": 11,
    "unitId": 1,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 1: 出师表与微分优化",
      "en": "Unit 1: Memorial & Differentiation"
    },
    "title": {
      "zh": "剑阁栈道",
      "en": "Jiange Pass"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-01"
  },
  {
    "id": 1113,
    "grade": 11,
    "unitId": 1,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 1: 出师表与微分优化",
      "en": "Unit 1: Memorial & Differentiation"
    },
    "title": {
      "zh": "粮仓极值",
      "en": "Granary Optimization"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-01"
  },
  {
    "id": 1121,
    "grade": 11,
    "unitId": 2,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 2: 屯田与定积分",
      "en": "Unit 2: Farming & Integration"
    },
    "title": {
      "zh": "测量农田",
      "en": "Surveying Farmland"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-01"
  },
  {
    "id": 1122,
    "grade": 11,
    "unitId": 2,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 2: 屯田与定积分",
      "en": "Unit 2: Farming & Integration"
    },
    "title": {
      "zh": "河道流量",
      "en": "River Flow"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-01"
  },
  {
    "id": 1123,
    "grade": 11,
    "unitId": 2,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 2: 屯田与定积分",
      "en": "Unit 2: Farming & Integration"
    },
    "title": {
      "zh": "屯田丈量",
      "en": "Field Measurement"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-02"
  },
  {
    "id": 1131,
    "grade": 11,
    "unitId": 3,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 3: 粮草序列",
      "en": "Unit 3: Supply Sequences"
    },
    "title": {
      "zh": "运粮序列",
      "en": "Supply Line"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1132,
    "grade": 11,
    "unitId": 3,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 3: 粮草序列",
      "en": "Unit 3: Supply Sequences"
    },
    "title": {
      "zh": "屯粮通项",
      "en": "Stockpile nth Term"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1133,
    "grade": 11,
    "unitId": 3,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 3: 粮草序列",
      "en": "Unit 3: Supply Sequences"
    },
    "title": {
      "zh": "军饷翻倍",
      "en": "Doubling Wages"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 1141,
    "grade": 11,
    "unitId": 4,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 4: 天下户籍·统计大计",
      "en": "Unit 4: National Census — The Great Count"
    },
    "title": {
      "zh": "各郡粮产",
      "en": "Prefecture Grain Yield"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-01"
  },
  {
    "id": 1142,
    "grade": 11,
    "unitId": 4,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 4: 天下户籍·统计大计",
      "en": "Unit 4: National Census — The Great Count"
    },
    "title": {
      "zh": "驻军兵力",
      "en": "Garrison Strength"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-02"
  },
  {
    "id": 1143,
    "grade": 11,
    "unitId": 4,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 4: 天下户籍·统计大计",
      "en": "Unit 4: National Census — The Great Count"
    },
    "title": {
      "zh": "常用兵器",
      "en": "Most Common Weapon"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-03"
  },
  {
    "id": 1144,
    "grade": 11,
    "unitId": 4,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 4: 天下户籍·统计大计",
      "en": "Unit 4: National Census — The Great Count"
    },
    "title": {
      "zh": "战损极差",
      "en": "Casualty Range"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-04"
  },
  {
    "id": 1151,
    "grade": 11,
    "unitId": 5,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 5: 战损清算·概率推演",
      "en": "Unit 5: War Damage Audit — Probability Analysis"
    },
    "title": {
      "zh": "攻城胜算",
      "en": "Siege Probability"
    },
    "topic": "Statistics",
    "kpId": "kp-8.2-01"
  },
  {
    "id": 1152,
    "grade": 11,
    "unitId": 5,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 5: 战损清算·概率推演",
      "en": "Unit 5: War Damage Audit — Probability Analysis"
    },
    "title": {
      "zh": "双路夹击",
      "en": "Two-Pronged Attack"
    },
    "topic": "Statistics",
    "kpId": "kp-8.3-03"
  },
  {
    "id": 1153,
    "grade": 11,
    "unitId": 5,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 5: 战损清算·概率推演",
      "en": "Unit 5: War Damage Audit — Probability Analysis"
    },
    "title": {
      "zh": "将领履历",
      "en": "Generals' Records"
    },
    "topic": "Statistics",
    "kpId": "kp-1.2-02"
  },
  {
    "id": 1154,
    "grade": 11,
    "unitId": 5,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 5: 战损清算·概率推演",
      "en": "Unit 5: War Damage Audit — Probability Analysis"
    },
    "title": {
      "zh": "斥候两探",
      "en": "Double Scouting"
    },
    "topic": "Statistics",
    "kpId": "kp-9.2-01"
  },
  {
    "id": 1161,
    "grade": 11,
    "unitId": 6,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 6: 行军向量·进退有据",
      "en": "Unit 6: March Vectors — Strategic Movement"
    },
    "title": {
      "zh": "两段行军",
      "en": "Two-Stage March"
    },
    "topic": "Geometry",
    "kpId": "kp-7.2-01"
  },
  {
    "id": 1162,
    "grade": 11,
    "unitId": 6,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 6: 行军向量·进退有据",
      "en": "Unit 6: March Vectors — Strategic Movement"
    },
    "title": {
      "zh": "补给倍增",
      "en": "Supply Route Scaling"
    },
    "topic": "Geometry",
    "kpId": "kp-7.2-02"
  },
  {
    "id": 1163,
    "grade": 11,
    "unitId": 6,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 6: 行军向量·进退有据",
      "en": "Unit 6: March Vectors — Strategic Movement"
    },
    "title": {
      "zh": "行军总距离",
      "en": "Total March Distance"
    },
    "topic": "Geometry",
    "kpId": "kp-7.3-01"
  },
  {
    "id": 1171,
    "grade": 11,
    "unitId": 7,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 7: 三国编年·数据图表",
      "en": "Unit 7: Chronicles of Three Kingdoms — Charts"
    },
    "title": {
      "zh": "分组均值",
      "en": "Grouped Mean"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-05"
  },
  {
    "id": 1172,
    "grade": 11,
    "unitId": 7,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 7: 三国编年·数据图表",
      "en": "Unit 7: Chronicles of Three Kingdoms — Charts"
    },
    "title": {
      "zh": "战损累积",
      "en": "Cumulative Casualties"
    },
    "topic": "Statistics",
    "kpId": "kp-9.6-01"
  },
  {
    "id": 1173,
    "grade": 11,
    "unitId": 7,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 7: 三国编年·数据图表",
      "en": "Unit 7: Chronicles of Three Kingdoms — Charts"
    },
    "title": {
      "zh": "四分位分析",
      "en": "Quartile Analysis"
    },
    "topic": "Statistics",
    "kpId": "kp-9.6-02"
  },
  {
    "id": 1181,
    "grade": 11,
    "unitId": 8,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 8: 六出祁山·微积分篇",
      "en": "Unit 8: Six Campaigns — Calculus"
    },
    "title": {
      "zh": "行军速率",
      "en": "March Rate"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-01"
  },
  {
    "id": 1182,
    "grade": 11,
    "unitId": 8,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 8: 六出祁山·微积分篇",
      "en": "Unit 8: Six Campaigns — Calculus"
    },
    "title": {
      "zh": "粮草总量",
      "en": "Total Supplies"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-02"
  },
  {
    "id": 1183,
    "grade": 11,
    "unitId": 8,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 8: 六出祁山·微积分篇",
      "en": "Unit 8: Six Campaigns — Calculus"
    },
    "title": {
      "zh": "行军补给",
      "en": "March Resupply"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-02"
  },
  {
    "id": 1191,
    "grade": 11,
    "unitId": 9,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 9: 八阵图·向量运算",
      "en": "Unit 9: Eight Formations — Vector Ops"
    },
    "title": {
      "zh": "阵法向量",
      "en": "Formation Vectors"
    },
    "topic": "Geometry",
    "kpId": "kp-7.4-01"
  },
  {
    "id": 1192,
    "grade": 11,
    "unitId": 9,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 9: 八阵图·向量运算",
      "en": "Unit 9: Eight Formations — Vector Ops"
    },
    "title": {
      "zh": "突围位移",
      "en": "Breakout Displacement"
    },
    "topic": "Geometry",
    "kpId": "kp-7.4-01"
  },
  {
    "id": 11101,
    "grade": 11,
    "unitId": 10,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 10: 赤壁遗策·高级三角",
      "en": "Unit 10: Legacy of Red Cliffs — Advanced Trig"
    },
    "title": {
      "zh": "斜岸测量",
      "en": "Oblique Shore Survey"
    },
    "topic": "Geometry",
    "kpId": "kp-6.3-01"
  },
  {
    "id": 11102,
    "grade": 11,
    "unitId": 10,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 10: 赤壁遗策·高级三角",
      "en": "Unit 10: Legacy of Red Cliffs — Advanced Trig"
    },
    "title": {
      "zh": "夹角攻防",
      "en": "Included Angle Battle"
    },
    "topic": "Geometry",
    "kpId": "kp-6.4-01"
  },
  {
    "id": 11103,
    "grade": 11,
    "unitId": 10,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 10: 赤壁遗策·高级三角",
      "en": "Unit 10: Legacy of Red Cliffs — Advanced Trig"
    },
    "title": {
      "zh": "战场测距",
      "en": "Battlefield Range"
    },
    "topic": "Geometry",
    "kpId": "kp-6.3-01"
  },
  {
    "id": 11111,
    "grade": 11,
    "unitId": 11,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 11: 隆中对策·函数图像",
      "en": "Unit 11: Longzhong Strategy — Function Graphs"
    },
    "title": {
      "zh": "抛物线顶点",
      "en": "Parabola Vertex"
    },
    "topic": "Functions",
    "kpId": "kp-2.10-01"
  },
  {
    "id": 11112,
    "grade": 11,
    "unitId": 11,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 11: 隆中对策·函数图像",
      "en": "Unit 11: Longzhong Strategy — Function Graphs"
    },
    "title": {
      "zh": "函数零点",
      "en": "Function Zeros"
    },
    "topic": "Functions",
    "kpId": "kp-2.10-02"
  },
  {
    "id": 11113,
    "grade": 11,
    "unitId": 11,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 11: 隆中对策·函数图像",
      "en": "Unit 11: Longzhong Strategy — Function Graphs"
    },
    "title": {
      "zh": "军需函数",
      "en": "Supply Function"
    },
    "topic": "Functions",
    "kpId": "kp-3.1-01"
  },
  {
    "id": 11201,
    "grade": 11,
    "unitId": 12,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 12: 正弦余弦定理",
      "en": "Unit 12: Sine & Cosine Rules"
    },
    "title": {
      "zh": "正弦定理·求边",
      "en": "Sine Rule — Find Side"
    },
    "topic": "Geometry",
    "kpId": "kp-6.5-01"
  },
  {
    "id": 11202,
    "grade": 11,
    "unitId": 12,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 12: 正弦余弦定理",
      "en": "Unit 12: Sine & Cosine Rules"
    },
    "title": {
      "zh": "余弦定理·求边",
      "en": "Cosine Rule — Find Side"
    },
    "topic": "Geometry",
    "kpId": "kp-6.5-02"
  },
  {
    "id": 11203,
    "grade": 11,
    "unitId": 12,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 12: 正弦余弦定理",
      "en": "Unit 12: Sine & Cosine Rules"
    },
    "title": {
      "zh": "余弦定理·求角",
      "en": "Cosine Rule — Find Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-6.5-03"
  },
  {
    "id": 11204,
    "grade": 11,
    "unitId": 12,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 12: 正弦余弦定理",
      "en": "Unit 12: Sine & Cosine Rules"
    },
    "title": {
      "zh": "三角形面积公式",
      "en": "Triangle Area Formula"
    },
    "topic": "Geometry",
    "kpId": "kp-6.5-07"
  },
  {
    "id": 11205,
    "grade": 11,
    "unitId": 13,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 13: 三维三角",
      "en": "Unit 13: 3D Trigonometry"
    },
    "title": {
      "zh": "三维勾股",
      "en": "3D Pythagoras"
    },
    "topic": "Geometry",
    "kpId": "kp-6.6-01"
  },
  {
    "id": 11206,
    "grade": 11,
    "unitId": 13,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 13: 三维三角",
      "en": "Unit 13: 3D Trigonometry"
    },
    "title": {
      "zh": "三维仰角",
      "en": "3D Elevation Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-6.6-02"
  },
  {
    "id": 11207,
    "grade": 11,
    "unitId": 14,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 14: 指数增减与根式",
      "en": "Unit 14: Exponential Growth & Surds"
    },
    "title": {
      "zh": "指数增长",
      "en": "Exponential Growth"
    },
    "topic": "Algebra",
    "kpId": "kp-1.17-01"
  },
  {
    "id": 11208,
    "grade": 11,
    "unitId": 14,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 14: 指数增减与根式",
      "en": "Unit 14: Exponential Growth & Surds"
    },
    "title": {
      "zh": "根式化简",
      "en": "Simplifying Surds"
    },
    "topic": "Algebra",
    "kpId": "kp-1.18-01"
  },
  {
    "id": 11209,
    "grade": 11,
    "unitId": 15,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 15: 曲线草图与垂直线",
      "en": "Unit 15: Curve Sketching & Perpendicular Lines"
    },
    "title": {
      "zh": "渐近线识别",
      "en": "Identifying Asymptotes"
    },
    "topic": "Algebra",
    "kpId": "kp-2.11-01"
  },
  {
    "id": 11210,
    "grade": 11,
    "unitId": 15,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 15: 曲线草图与垂直线",
      "en": "Unit 15: Curve Sketching & Perpendicular Lines"
    },
    "title": {
      "zh": "函数平移",
      "en": "Function Translation"
    },
    "topic": "Algebra",
    "kpId": "kp-2.11-02"
  },
  {
    "id": 11211,
    "grade": 11,
    "unitId": 15,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 15: 曲线草图与垂直线",
      "en": "Unit 15: Curve Sketching & Perpendicular Lines"
    },
    "title": {
      "zh": "垂直线斜率",
      "en": "Perpendicular Line Gradient"
    },
    "topic": "Algebra",
    "kpId": "kp-3.7-01"
  },
  {
    "id": 11212,
    "grade": 11,
    "unitId": 16,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 16: 高级比例",
      "en": "Unit 16: Advanced Proportion"
    },
    "title": {
      "zh": "幂次比例",
      "en": "Power Proportion"
    },
    "topic": "Algebra",
    "kpId": "kp-2.8-02"
  },
  {
    "id": 11213,
    "grade": 11,
    "unitId": 17,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 17: 三角学进阶",
      "en": "Unit 17: Trig Advanced"
    },
    "title": {
      "zh": "三角求边",
      "en": "Trig Side-Finding"
    },
    "topic": "Geometry",
    "kpId": "kp-6.2-02"
  },
  {
    "id": 11214,
    "grade": 11,
    "unitId": 17,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 17: 三角学进阶",
      "en": "Unit 17: Trig Advanced"
    },
    "title": {
      "zh": "反三角求角",
      "en": "Inverse Trig Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-6.2-03"
  },
  {
    "id": 11215,
    "grade": 11,
    "unitId": 17,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 17: 三角学进阶",
      "en": "Unit 17: Trig Advanced"
    },
    "title": {
      "zh": "精确三角值",
      "en": "Exact Trig Values"
    },
    "topic": "Geometry",
    "kpId": "kp-6.3-02"
  },
  {
    "id": 11216,
    "grade": 11,
    "unitId": 17,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 17: 三角学进阶",
      "en": "Unit 17: Trig Advanced"
    },
    "title": {
      "zh": "三角函数值",
      "en": "Trig Function Values"
    },
    "topic": "Geometry",
    "kpId": "kp-6.4-02"
  },
  {
    "id": 11217,
    "grade": 11,
    "unitId": 17,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 17: 三角学进阶",
      "en": "Unit 17: Trig Advanced"
    },
    "title": {
      "zh": "正弦周期",
      "en": "Sine Period"
    },
    "topic": "Geometry",
    "kpId": "kp-6.4-03"
  },
  {
    "id": 11218,
    "grade": 11,
    "unitId": 17,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 17: 三角学进阶",
      "en": "Unit 17: Trig Advanced"
    },
    "title": {
      "zh": "三角面积",
      "en": "Trig Area"
    },
    "topic": "Geometry",
    "kpId": "kp-6.5-04"
  },
  {
    "id": 11219,
    "grade": 11,
    "unitId": 17,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 17: 三角学进阶",
      "en": "Unit 17: Trig Advanced"
    },
    "title": {
      "zh": "正弦定理·进阶",
      "en": "Sine Rule Advanced"
    },
    "topic": "Geometry",
    "kpId": "kp-6.5-05"
  },
  {
    "id": 11220,
    "grade": 11,
    "unitId": 17,
    "order": 8,
    "unitTitle": {
      "zh": "Unit 17: 三角学进阶",
      "en": "Unit 17: Trig Advanced"
    },
    "title": {
      "zh": "余弦定理·进阶",
      "en": "Cosine Rule Advanced"
    },
    "topic": "Geometry",
    "kpId": "kp-6.5-06"
  },
  {
    "id": 11221,
    "grade": 11,
    "unitId": 18,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 18: 函数进阶",
      "en": "Unit 18: Functions Advanced"
    },
    "title": {
      "zh": "反函数推演",
      "en": "Inverse Function"
    },
    "topic": "Algebra",
    "kpId": "kp-2.13-02"
  },
  {
    "id": 11222,
    "grade": 11,
    "unitId": 18,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 18: 函数进阶",
      "en": "Unit 18: Functions Advanced"
    },
    "title": {
      "zh": "复合函数",
      "en": "Composite Functions"
    },
    "topic": "Algebra",
    "kpId": "kp-2.13-03"
  },
  {
    "id": 11223,
    "grade": 11,
    "unitId": 18,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 18: 函数进阶",
      "en": "Unit 18: Functions Advanced"
    },
    "title": {
      "zh": "定义域与值域",
      "en": "Domain & Range"
    },
    "topic": "Algebra",
    "kpId": "kp-2.13-04"
  },
  {
    "id": 11224,
    "grade": 11,
    "unitId": 18,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 18: 函数进阶",
      "en": "Unit 18: Functions Advanced"
    },
    "title": {
      "zh": "曲线交点",
      "en": "Curve Intersections"
    },
    "topic": "Algebra",
    "kpId": "kp-2.11-03"
  },
  {
    "id": 11225,
    "grade": 11,
    "unitId": 19,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 19: 向量进阶",
      "en": "Unit 19: Vectors Advanced"
    },
    "title": {
      "zh": "向量模长",
      "en": "Vector Magnitude"
    },
    "topic": "Geometry",
    "kpId": "kp-7.2-03"
  },
  {
    "id": 11226,
    "grade": 11,
    "unitId": 19,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 19: 向量进阶",
      "en": "Unit 19: Vectors Advanced"
    },
    "title": {
      "zh": "向量几何",
      "en": "Vector Geometry"
    },
    "topic": "Geometry",
    "kpId": "kp-7.4-02"
  }
] as MissionSummary[];
