import type { MissionSummary } from '../../types';

// Auto-generated by scripts/generate-mission-summaries.ts
export const MISSION_SUMMARIES_Y12: MissionSummary[] = [
  {
    "id": 1211,
    "grade": 12,
    "unitId": 1,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 1: 归晋与综合微积分",
      "en": "Unit 1: Unification & Advanced Calculus"
    },
    "title": {
      "zh": "最后的防线",
      "en": "The Final Stand"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-01"
  },
  {
    "id": 1221,
    "grade": 12,
    "unitId": 2,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 2: 战后统计",
      "en": "Unit 2: Post-War Statistics"
    },
    "title": {
      "zh": "胜率评估",
      "en": "Win Rate Assessment"
    },
    "topic": "Statistics",
    "kpId": "kp-8.3-02"
  },
  {
    "id": 1212,
    "grade": 12,
    "unitId": 1,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 1: 归晋与综合微积分",
      "en": "Unit 1: Unification & Advanced Calculus"
    },
    "title": {
      "zh": "攻城速率",
      "en": "Siege Rate"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-01"
  },
  {
    "id": 1222,
    "grade": 12,
    "unitId": 2,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 2: 战后统计",
      "en": "Unit 2: Post-War Statistics"
    },
    "title": {
      "zh": "军粮盘点",
      "en": "Grain Stocktake"
    },
    "topic": "Statistics",
    "kpId": "kp-8.2-01"
  },
  {
    "id": 1231,
    "grade": 12,
    "unitId": 3,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 3: 三分归晋·综合篇",
      "en": "Unit 3: Reunification — Synthesis"
    },
    "title": {
      "zh": "三国均势",
      "en": "Balance of Power"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-08"
  },
  {
    "id": 1232,
    "grade": 12,
    "unitId": 3,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 3: 三分归晋·综合篇",
      "en": "Unit 3: Reunification — Synthesis"
    },
    "title": {
      "zh": "国力函数",
      "en": "National Power Function"
    },
    "topic": "Functions",
    "kpId": "kp-2.13-01"
  },
  {
    "id": 1233,
    "grade": 12,
    "unitId": 3,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 3: 三分归晋·综合篇",
      "en": "Unit 3: Reunification — Synthesis"
    },
    "title": {
      "zh": "最终防线",
      "en": "The Final Defense"
    },
    "topic": "Geometry",
    "kpId": "kp-6.2-01"
  },
  {
    "id": 1241,
    "grade": 12,
    "unitId": 4,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 4: 三维战场·向量",
      "en": "Unit 4: 3D Battlefield — Vectors"
    },
    "title": {
      "zh": "空间行军",
      "en": "Spatial March"
    },
    "topic": "Geometry",
    "kpId": "kp-7.2-01"
  },
  {
    "id": 1242,
    "grade": 12,
    "unitId": 4,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 4: 三维战场·向量",
      "en": "Unit 4: 3D Battlefield — Vectors"
    },
    "title": {
      "zh": "炮火交叉",
      "en": "Crossfire Vectors"
    },
    "topic": "Geometry",
    "kpId": "kp-7.2-01"
  },
  {
    "id": 1251,
    "grade": 12,
    "unitId": 5,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 5: 天下计量·积分面积",
      "en": "Unit 5: Grand Measurement — Integral Area"
    },
    "title": {
      "zh": "屯田面积",
      "en": "Farm Area"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-02"
  },
  {
    "id": 1252,
    "grade": 12,
    "unitId": 5,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 5: 天下计量·积分面积",
      "en": "Unit 5: Grand Measurement — Integral Area"
    },
    "title": {
      "zh": "城墙曲面",
      "en": "Curved Rampart"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-02"
  },
  {
    "id": 1253,
    "grade": 12,
    "unitId": 5,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 5: 天下计量·积分面积",
      "en": "Unit 5: Grand Measurement — Integral Area"
    },
    "title": {
      "zh": "四次幂堆积",
      "en": "Quartic Accumulation"
    },
    "topic": "Calculus",
    "kpId": "kp-2.12-02"
  },
  {
    "id": 1261,
    "grade": 12,
    "unitId": 6,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 6: 轨迹与作图",
      "en": "Unit 6: Constructions & Loci"
    },
    "title": {
      "zh": "安全区域",
      "en": "Safe Zone"
    },
    "topic": "Geometry",
    "kpId": "kp-4.8-01"
  },
  {
    "id": 1262,
    "grade": 12,
    "unitId": 6,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 6: 轨迹与作图",
      "en": "Unit 6: Constructions & Loci"
    },
    "title": {
      "zh": "两城等距",
      "en": "Equidistant Border"
    },
    "topic": "Geometry",
    "kpId": "kp-4.8-02"
  },
  {
    "id": 1263,
    "grade": 12,
    "unitId": 7,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 7: 轨迹进阶",
      "en": "Unit 7: Advanced Loci"
    },
    "title": {
      "zh": "轨迹交点",
      "en": "Loci Intersection"
    },
    "topic": "Geometry",
    "kpId": "kp-4.8-03"
  }
] as MissionSummary[];
