import type { MissionSummary } from '../../types';

// Auto-generated by scripts/generate-mission-summaries.ts
export const MISSION_SUMMARIES_Y7: MissionSummary[] = [
  {
    "id": 698,
    "grade": 7,
    "unitId": 0,
    "order": -2,
    "unitTitle": {
      "zh": "Unit 0: 桃园点兵·数论篇",
      "en": "Unit 0: Peach Garden — Number Theory"
    },
    "title": {
      "zh": "点兵编队",
      "en": "Troop Formation Count"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-02"
  },
  {
    "id": 699,
    "grade": 7,
    "unitId": 0,
    "order": -1,
    "unitTitle": {
      "zh": "Unit 0: 桃园点兵·数论篇",
      "en": "Unit 0: Peach Garden — Number Theory"
    },
    "title": {
      "zh": "选拔亲卫",
      "en": "Selecting Elite Guards"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-01"
  },
  {
    "id": 700,
    "grade": 7,
    "unitId": 0,
    "order": 0,
    "unitTitle": {
      "zh": "Unit 0: 桃园点兵·数论篇",
      "en": "Unit 0: Peach Garden — Number Theory"
    },
    "title": {
      "zh": "拆解兵力",
      "en": "Breaking Down Forces"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-08"
  },
  {
    "id": 701,
    "grade": 7,
    "unitId": 0,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 0: 桃园点兵·数论篇",
      "en": "Unit 0: Peach Garden — Number Theory"
    },
    "title": {
      "zh": "整编队伍",
      "en": "Organizing Troops"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-08"
  },
  {
    "id": 702,
    "grade": 7,
    "unitId": 0,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 0: 桃园点兵·数论篇",
      "en": "Unit 0: Peach Garden — Number Theory"
    },
    "title": {
      "zh": "巡营排班",
      "en": "Patrol Schedule"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-09"
  },
  {
    "id": 703,
    "grade": 7,
    "unitId": 0,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 0: 桃园点兵·数论篇",
      "en": "Unit 0: Peach Garden — Number Theory"
    },
    "title": {
      "zh": "平分军粮",
      "en": "Dividing Grain Equally"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-08"
  },
  {
    "id": 704,
    "grade": 7,
    "unitId": 0,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 0A: 行军算账·正负数篇",
      "en": "Unit 0A: March Accounting — Integers"
    },
    "title": {
      "zh": "粮草盈亏",
      "en": "Grain Surplus & Loss"
    },
    "topic": "Algebra",
    "kpId": "kp-1.6-01"
  },
  {
    "id": 705,
    "grade": 7,
    "unitId": 0,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 0A: 行军算账·正负数篇",
      "en": "Unit 0A: March Accounting — Integers"
    },
    "title": {
      "zh": "连续损失",
      "en": "Consecutive Losses"
    },
    "topic": "Algebra",
    "kpId": "kp-1.6-01"
  },
  {
    "id": 706,
    "grade": 7,
    "unitId": 0,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 0A: 行军算账·正负数篇",
      "en": "Unit 0A: March Accounting — Integers"
    },
    "title": {
      "zh": "攻守得失",
      "en": "Gains and Losses"
    },
    "topic": "Algebra",
    "kpId": "kp-1.6-02"
  },
  {
    "id": 693,
    "grade": 7,
    "unitId": 0,
    "order": 6.5,
    "unitTitle": {
      "zh": "Unit 0A: 行军算账·正负数篇",
      "en": "Unit 0A: March Accounting — Integers"
    },
    "title": {
      "zh": "敌退我进",
      "en": "Enemy Retreats, We Advance"
    },
    "topic": "Algebra",
    "kpId": "kp-1.6-03"
  },
  {
    "id": 697,
    "grade": 7,
    "unitId": 0,
    "order": 6.8,
    "unitTitle": {
      "zh": "Unit 0B: 军粮分配·分数篇",
      "en": "Unit 0B: Grain Division — Fractions"
    },
    "title": {
      "zh": "分饼入门",
      "en": "Sharing the Pie"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-01"
  },
  {
    "id": 707,
    "grade": 7,
    "unitId": 0,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 0B: 军粮分配·分数篇",
      "en": "Unit 0B: Grain Division — Fractions"
    },
    "title": {
      "zh": "合并粮草",
      "en": "Combining Grain"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-01"
  },
  {
    "id": 708,
    "grade": 7,
    "unitId": 0,
    "order": 8,
    "unitTitle": {
      "zh": "Unit 0B: 军粮分配·分数篇",
      "en": "Unit 0B: Grain Division — Fractions"
    },
    "title": {
      "zh": "消耗军粮",
      "en": "Consuming Grain"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-01"
  },
  {
    "id": 692,
    "grade": 7,
    "unitId": 0,
    "order": 8.3,
    "unitTitle": {
      "zh": "Unit 0B: 军粮分配·分数篇",
      "en": "Unit 0B: Grain Division — Fractions"
    },
    "title": {
      "zh": "整箱拆零",
      "en": "Unpacking Crates"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-01"
  },
  {
    "id": 690,
    "grade": 7,
    "unitId": 0,
    "order": 8.6,
    "unitTitle": {
      "zh": "Unit 0B: 军粮分配·分数篇",
      "en": "Unit 0B: Grain Division — Fractions"
    },
    "title": {
      "zh": "散装装箱",
      "en": "Repacking Loose Items"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-01"
  },
  {
    "id": 709,
    "grade": 7,
    "unitId": 0,
    "order": 9,
    "unitTitle": {
      "zh": "Unit 0B: 军粮分配·分数篇",
      "en": "Unit 0B: Grain Division — Fractions"
    },
    "title": {
      "zh": "粮草翻倍",
      "en": "Grain Multiplication"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-02"
  },
  {
    "id": 710,
    "grade": 7,
    "unitId": 0,
    "order": 10,
    "unitTitle": {
      "zh": "Unit 0B: 军粮分配·分数篇",
      "en": "Unit 0B: Grain Division — Fractions"
    },
    "title": {
      "zh": "分粮入户",
      "en": "Grain Division"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-02"
  },
  {
    "id": 694,
    "grade": 7,
    "unitId": 0,
    "order": 10.5,
    "unitTitle": {
      "zh": "Unit 0B: 军粮分配·分数篇",
      "en": "Unit 0B: Grain Division — Fractions"
    },
    "title": {
      "zh": "情报三译",
      "en": "Intelligence in Three Formats"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-03"
  },
  {
    "id": 713,
    "grade": 7,
    "unitId": 0,
    "order": 11,
    "unitTitle": {
      "zh": "Unit 0C: 排兵布阵·幂与根篇",
      "en": "Unit 0C: Battle Formation — Powers & Roots"
    },
    "title": {
      "zh": "方阵操练",
      "en": "Square Formation Drill"
    },
    "topic": "Algebra",
    "kpId": "kp-1.3-01"
  },
  {
    "id": 714,
    "grade": 7,
    "unitId": 0,
    "order": 12,
    "unitTitle": {
      "zh": "Unit 0C: 排兵布阵·幂与根篇",
      "en": "Unit 0C: Battle Formation — Powers & Roots"
    },
    "title": {
      "zh": "粮箱码垛",
      "en": "Stacking Supply Crates"
    },
    "topic": "Algebra",
    "kpId": "kp-1.3-02"
  },
  {
    "id": 715,
    "grade": 7,
    "unitId": 0,
    "order": 13,
    "unitTitle": {
      "zh": "Unit 0C: 排兵布阵·幂与根篇",
      "en": "Unit 0C: Battle Formation — Powers & Roots"
    },
    "title": {
      "zh": "侦察敌阵",
      "en": "Scouting Enemy Formation"
    },
    "topic": "Algebra",
    "kpId": "kp-1.3-03"
  },
  {
    "id": 716,
    "grade": 7,
    "unitId": 0,
    "order": 14,
    "unitTitle": {
      "zh": "Unit 0C: 排兵布阵·幂与根篇",
      "en": "Unit 0C: Battle Formation — Powers & Roots"
    },
    "title": {
      "zh": "综合考核",
      "en": "Combined Assessment"
    },
    "topic": "Algebra",
    "kpId": "kp-1.3-03"
  },
  {
    "id": 695,
    "grade": 7,
    "unitId": 1,
    "order": 0,
    "unitTitle": {
      "zh": "Unit 1: 结义与代数入门",
      "en": "Unit 1: Oath & Intro to Algebra"
    },
    "title": {
      "zh": "军令如山",
      "en": "Orders of Command"
    },
    "topic": "Algebra",
    "kpId": "kp-1.6-03"
  },
  {
    "id": 691,
    "grade": 7,
    "unitId": 1,
    "order": 0.5,
    "unitTitle": {
      "zh": "Unit 1: 结义与代数入门",
      "en": "Unit 1: Oath & Intro to Algebra"
    },
    "title": {
      "zh": "括号将令",
      "en": "Brackets Override"
    },
    "topic": "Algebra",
    "kpId": "kp-1.6-03"
  },
  {
    "id": 711,
    "grade": 7,
    "unitId": 1,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 1: 结义与代数入门",
      "en": "Unit 1: Oath & Intro to Algebra"
    },
    "title": {
      "zh": "桃园结义",
      "en": "Oath in the Garden"
    },
    "topic": "Algebra",
    "kpId": "kp-2.1-01"
  },
  {
    "id": 712,
    "grade": 7,
    "unitId": 1,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 1: 结义与代数入门",
      "en": "Unit 1: Oath & Intro to Algebra"
    },
    "title": {
      "zh": "招兵买马",
      "en": "Recruiting Soldiers"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-01"
  },
  {
    "id": 696,
    "grade": 7,
    "unitId": 1,
    "order": 2.5,
    "unitTitle": {
      "zh": "Unit 1: 结义与代数入门",
      "en": "Unit 1: Oath & Intro to Algebra"
    },
    "title": {
      "zh": "攻城双关",
      "en": "Two-Gate Siege"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-02"
  },
  {
    "id": 717,
    "grade": 7,
    "unitId": 1,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 1: 结义与代数入门",
      "en": "Unit 1: Oath & Intro to Algebra"
    },
    "title": {
      "zh": "军情密码",
      "en": "Military Code"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-01"
  },
  {
    "id": 718,
    "grade": 7,
    "unitId": 1,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 1: 结义与代数入门",
      "en": "Unit 1: Oath & Intro to Algebra"
    },
    "title": {
      "zh": "投石车射程",
      "en": "Catapult Range"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-02"
  },
  {
    "id": 719,
    "grade": 7,
    "unitId": 1,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 1: 结义与代数入门",
      "en": "Unit 1: Oath & Intro to Algebra"
    },
    "title": {
      "zh": "合兵一处",
      "en": "Combining Forces"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-03"
  },
  {
    "id": 721,
    "grade": 7,
    "unitId": 2,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 2: 粮草调度与比例",
      "en": "Unit 2: Logistics & Ratios"
    },
    "title": {
      "zh": "分配军粮",
      "en": "Distributing Grain"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-01"
  },
  {
    "id": 722,
    "grade": 7,
    "unitId": 2,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 2: 粮草调度与比例",
      "en": "Unit 2: Logistics & Ratios"
    },
    "title": {
      "zh": "征调民夫",
      "en": "Drafting Laborers"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-01"
  },
  {
    "id": 723,
    "grade": 7,
    "unitId": 2,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 2: 粮草调度与比例",
      "en": "Unit 2: Logistics & Ratios"
    },
    "title": {
      "zh": "军饷提成",
      "en": "Military Stipend"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-02"
  },
  {
    "id": 724,
    "grade": 7,
    "unitId": 2,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 2: 粮草调度与比例",
      "en": "Unit 2: Logistics & Ratios"
    },
    "title": {
      "zh": "粮价涨跌",
      "en": "Grain Price Change"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-03"
  },
  {
    "id": 725,
    "grade": 7,
    "unitId": 2,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 2: 粮草调度与比例",
      "en": "Unit 2: Logistics & Ratios"
    },
    "title": {
      "zh": "精简军令",
      "en": "Simplify Orders"
    },
    "topic": "Algebra",
    "kpId": "kp-1.11-01"
  },
  {
    "id": 726,
    "grade": 7,
    "unitId": 2,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 2: 粮草调度与比例",
      "en": "Unit 2: Logistics & Ratios"
    },
    "title": {
      "zh": "战利分配",
      "en": "Sharing War Spoils"
    },
    "topic": "Algebra",
    "kpId": "kp-1.11-02"
  },
  {
    "id": 731,
    "grade": 7,
    "unitId": 3,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 3: 关隘与角度",
      "en": "Unit 3: Passes & Angles"
    },
    "title": {
      "zh": "据守虎牢关",
      "en": "Defending Hulao Pass"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-01"
  },
  {
    "id": 732,
    "grade": 7,
    "unitId": 3,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 3: 关隘与角度",
      "en": "Unit 3: Passes & Angles"
    },
    "title": {
      "zh": "交叉火力",
      "en": "Crossfire"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-01"
  },
  {
    "id": 733,
    "grade": 7,
    "unitId": 3,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 3: 关隘与角度",
      "en": "Unit 3: Passes & Angles"
    },
    "title": {
      "zh": "八卦阵位",
      "en": "Eight Trigrams Position"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-01"
  },
  {
    "id": 734,
    "grade": 7,
    "unitId": 3,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 3: 关隘与角度",
      "en": "Unit 3: Passes & Angles"
    },
    "title": {
      "zh": "三角旗阵",
      "en": "Triangular Banner"
    },
    "topic": "Geometry",
    "kpId": "kp-4.3-01"
  },
  {
    "id": 735,
    "grade": 7,
    "unitId": 3,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 3: 关隘与角度",
      "en": "Unit 3: Passes & Angles"
    },
    "title": {
      "zh": "瞭望全景",
      "en": "Watchtower Panorama"
    },
    "topic": "Geometry",
    "kpId": "kp-4.3-02"
  },
  {
    "id": 745,
    "grade": 7,
    "unitId": 3,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 3A: 战场地图·坐标篇",
      "en": "Unit 3A: Battlefield Map — Coordinates"
    },
    "title": {
      "zh": "读图定位",
      "en": "Map Reading"
    },
    "topic": "Geometry",
    "kpId": "kp-3.1-01"
  },
  {
    "id": 746,
    "grade": 7,
    "unitId": 3,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 3A: 战场地图·坐标篇",
      "en": "Unit 3A: Battlefield Map — Coordinates"
    },
    "title": {
      "zh": "四象限侦察",
      "en": "Four Quadrant Recon"
    },
    "topic": "Geometry",
    "kpId": "kp-3.1-02"
  },
  {
    "id": 741,
    "grade": 7,
    "unitId": 4,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 4: 行军数列·序列篇",
      "en": "Unit 4: March Sequence — Sequences"
    },
    "title": {
      "zh": "增兵步伐",
      "en": "Troop Buildup Pattern"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-01"
  },
  {
    "id": 742,
    "grade": 7,
    "unitId": 4,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 4: 行军数列·序列篇",
      "en": "Unit 4: March Sequence — Sequences"
    },
    "title": {
      "zh": "远征推算",
      "en": "Expedition Projection"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-02"
  },
  {
    "id": 743,
    "grade": 7,
    "unitId": 4,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 4: 行军数列·序列篇",
      "en": "Unit 4: March Sequence — Sequences"
    },
    "title": {
      "zh": "粮草日减",
      "en": "Dwindling Supplies"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-03"
  },
  {
    "id": 751,
    "grade": 7,
    "unitId": 5,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 5: 斥候估算·近似值篇",
      "en": "Unit 5: Scout Estimation — Rounding"
    },
    "title": {
      "zh": "斥候报数",
      "en": "Scout Headcount"
    },
    "topic": "Algebra",
    "kpId": "kp-1.9-01"
  },
  {
    "id": 752,
    "grade": 7,
    "unitId": 5,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 5: 斥候估算·近似值篇",
      "en": "Unit 5: Scout Estimation — Rounding"
    },
    "title": {
      "zh": "大军估数",
      "en": "Army Estimate"
    },
    "topic": "Algebra",
    "kpId": "kp-1.9-02"
  },
  {
    "id": 761,
    "grade": 7,
    "unitId": 6,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 6: 营寨丈量·周长与面积篇",
      "en": "Unit 6: Camp Survey — Perimeter & Area"
    },
    "title": {
      "zh": "围栅建营",
      "en": "Building the Camp Fence"
    },
    "topic": "Geometry",
    "kpId": "kp-4.5-01"
  },
  {
    "id": 762,
    "grade": 7,
    "unitId": 6,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 6: 营寨丈量·周长与面积篇",
      "en": "Unit 6: Camp Survey — Perimeter & Area"
    },
    "title": {
      "zh": "营地面积",
      "en": "Camp Ground Area"
    },
    "topic": "Geometry",
    "kpId": "kp-4.5-02"
  },
  {
    "id": 763,
    "grade": 7,
    "unitId": 6,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 6: 营寨丈量·周长与面积篇",
      "en": "Unit 6: Camp Survey — Perimeter & Area"
    },
    "title": {
      "zh": "三角旗帜",
      "en": "Triangular Banner"
    },
    "topic": "Geometry",
    "kpId": "kp-4.5-02"
  },
  {
    "id": 764,
    "grade": 7,
    "unitId": 6,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 6: 营寨丈量·周长与面积篇",
      "en": "Unit 6: Camp Survey — Perimeter & Area"
    },
    "title": {
      "zh": "围栅反推",
      "en": "Fence Reverse Problem"
    },
    "topic": "Geometry",
    "kpId": "kp-4.5-01"
  },
  {
    "id": 765,
    "grade": 7,
    "unitId": 6,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 6: 营寨丈量·周长与面积篇",
      "en": "Unit 6: Camp Survey — Perimeter & Area"
    },
    "title": {
      "zh": "营地蓝图",
      "en": "Camp Blueprint"
    },
    "topic": "Geometry",
    "kpId": "kp-2.2-01"
  },
  {
    "id": 770,
    "grade": 7,
    "unitId": 7,
    "order": 0,
    "unitTitle": {
      "zh": "Unit 7: 战后统计·数据篇",
      "en": "Unit 7: Post-battle Stats — Data"
    },
    "title": {
      "zh": "兵器清点",
      "en": "Weapon Inventory"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-01"
  },
  {
    "id": 771,
    "grade": 7,
    "unitId": 7,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 7: 战后统计·数据篇",
      "en": "Unit 7: Post-battle Stats — Data"
    },
    "title": {
      "zh": "平均战力",
      "en": "Average Strength"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-01"
  },
  {
    "id": 772,
    "grade": 7,
    "unitId": 7,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 7: 战后统计·数据篇",
      "en": "Unit 7: Post-battle Stats — Data"
    },
    "title": {
      "zh": "中位排名",
      "en": "Median Rank"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-02"
  },
  {
    "id": 773,
    "grade": 7,
    "unitId": 7,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 7: 战后统计·数据篇",
      "en": "Unit 7: Post-battle Stats — Data"
    },
    "title": {
      "zh": "战力差距",
      "en": "Strength Spread"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-03"
  },
  {
    "id": 774,
    "grade": 7,
    "unitId": 8,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 8: 排兵布阵·有序篇",
      "en": "Unit 8: Formation Order"
    },
    "title": {
      "zh": "寒冬行军",
      "en": "Winter March"
    },
    "topic": "Algebra",
    "kpId": "kp-1.5-01"
  },
  {
    "id": 775,
    "grade": 7,
    "unitId": 8,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 8: 排兵布阵·有序篇",
      "en": "Unit 8: Formation Order"
    },
    "title": {
      "zh": "粮草排序",
      "en": "Supply Ranking"
    },
    "topic": "Algebra",
    "kpId": "kp-1.5-02"
  },
  {
    "id": 776,
    "grade": 7,
    "unitId": 8,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 8: 排兵布阵·有序篇",
      "en": "Unit 8: Formation Order"
    },
    "title": {
      "zh": "埋伏范围",
      "en": "Ambush Range"
    },
    "topic": "Algebra",
    "kpId": "kp-1.5-03"
  },
  {
    "id": 777,
    "grade": 7,
    "unitId": 9,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 9: 军中时辰·时间篇",
      "en": "Unit 9: Military Timekeeping"
    },
    "title": {
      "zh": "行军计时",
      "en": "March Timer"
    },
    "topic": "Algebra",
    "kpId": "kp-1.15-01"
  },
  {
    "id": 778,
    "grade": 7,
    "unitId": 9,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 9: 军中时辰·时间篇",
      "en": "Unit 9: Military Timekeeping"
    },
    "title": {
      "zh": "军令时刻",
      "en": "Military Orders Clock"
    },
    "topic": "Algebra",
    "kpId": "kp-1.15-02"
  },
  {
    "id": 779,
    "grade": 7,
    "unitId": 9,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 9: 军中时辰·时间篇",
      "en": "Unit 9: Military Timekeeping"
    },
    "title": {
      "zh": "跨境谍报",
      "en": "Cross-border Intelligence"
    },
    "topic": "Algebra",
    "kpId": "kp-1.15-03"
  },
  {
    "id": 780,
    "grade": 7,
    "unitId": 10,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 10: 军饷利息·货币篇",
      "en": "Unit 10: Military Treasury — Money"
    },
    "title": {
      "zh": "军饷单利",
      "en": "Simple Interest Stipend"
    },
    "topic": "Algebra",
    "kpId": "kp-1.16-01"
  },
  {
    "id": 781,
    "grade": 7,
    "unitId": 10,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 10: 军饷利息·货币篇",
      "en": "Unit 10: Military Treasury — Money"
    },
    "title": {
      "zh": "复利增值",
      "en": "Compound Growth"
    },
    "topic": "Algebra",
    "kpId": "kp-1.16-02"
  },
  {
    "id": 782,
    "grade": 7,
    "unitId": 11,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 11: 度量衡·单位篇",
      "en": "Unit 11: Weights & Measures — Units"
    },
    "title": {
      "zh": "丈量疆土",
      "en": "Measuring Territory"
    },
    "topic": "Algebra",
    "kpId": "kp-5.1-01"
  },
  {
    "id": 783,
    "grade": 7,
    "unitId": 11,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 11: 度量衡·单位篇",
      "en": "Unit 11: Weights & Measures — Units"
    },
    "title": {
      "zh": "粮秣称重",
      "en": "Weighing Supplies"
    },
    "topic": "Algebra",
    "kpId": "kp-5.1-02"
  },
  {
    "id": 784,
    "grade": 7,
    "unitId": 11,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 11: 度量衡·单位篇",
      "en": "Unit 11: Weights & Measures — Units"
    },
    "title": {
      "zh": "营帐面积",
      "en": "Camp Area"
    },
    "topic": "Algebra",
    "kpId": "kp-5.1-03"
  },
  {
    "id": 785,
    "grade": 7,
    "unitId": 12,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 12: 数的类型进阶",
      "en": "Unit 12: Advanced Number Types"
    },
    "title": {
      "zh": "方阵点兵",
      "en": "Square Formation Drill"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-03"
  },
  {
    "id": 786,
    "grade": 7,
    "unitId": 12,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 12: 数的类型进阶",
      "en": "Unit 12: Advanced Number Types"
    },
    "title": {
      "zh": "奇偶药方",
      "en": "Odd-Even Elixir"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-04"
  },
  {
    "id": 787,
    "grade": 7,
    "unitId": 12,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 12: 数的类型进阶",
      "en": "Unit 12: Advanced Number Types"
    },
    "title": {
      "zh": "缩放还原术",
      "en": "Shrink-Restore Technique"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-05"
  },
  {
    "id": 788,
    "grade": 7,
    "unitId": 12,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 12: 数的类型进阶",
      "en": "Unit 12: Advanced Number Types"
    },
    "title": {
      "zh": "分糖编队",
      "en": "Candy Division Drill"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-06"
  },
  {
    "id": 789,
    "grade": 7,
    "unitId": 12,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 12: 数的类型进阶",
      "en": "Unit 12: Advanced Number Types"
    },
    "title": {
      "zh": "公交同站",
      "en": "Bus Stop Rendezvous"
    },
    "topic": "Algebra",
    "kpId": "kp-1.1-07"
  },
  {
    "id": 790,
    "grade": 7,
    "unitId": 13,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 13: 集合与韦恩图",
      "en": "Unit 13: Sets & Venn Diagrams"
    },
    "title": {
      "zh": "校场分队",
      "en": "Training Ground Sorting"
    },
    "topic": "Algebra",
    "kpId": "kp-1.2-01"
  },
  {
    "id": 791,
    "grade": 7,
    "unitId": 13,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 13: 集合与韦恩图",
      "en": "Unit 13: Sets & Venn Diagrams"
    },
    "title": {
      "zh": "三军合围",
      "en": "Three-Army Encirclement"
    },
    "topic": "Algebra",
    "kpId": "kp-1.2-03"
  },
  {
    "id": 792,
    "grade": 7,
    "unitId": 13,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 13: 集合与韦恩图",
      "en": "Unit 13: Sets & Venn Diagrams"
    },
    "title": {
      "zh": "并集清点",
      "en": "Union Head Count"
    },
    "topic": "Algebra",
    "kpId": "kp-1.2-04"
  },
  {
    "id": 793,
    "grade": 7,
    "unitId": 13,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 13: 集合与韦恩图",
      "en": "Unit 13: Sets & Venn Diagrams"
    },
    "title": {
      "zh": "韦恩图实战",
      "en": "Venn Diagram Word Problem"
    },
    "topic": "Algebra",
    "kpId": "kp-1.2-05"
  },
  {
    "id": 794,
    "grade": 7,
    "unitId": 14,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 14: 进阶运算",
      "en": "Unit 14: Advanced Operations"
    },
    "title": {
      "zh": "折扣谍报",
      "en": "Discount Intelligence"
    },
    "topic": "Algebra",
    "kpId": "kp-1.4-04"
  },
  {
    "id": 795,
    "grade": 7,
    "unitId": 14,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 14: 进阶运算",
      "en": "Unit 14: Advanced Operations"
    },
    "title": {
      "zh": "小数陷阱",
      "en": "Decimal Trap"
    },
    "topic": "Algebra",
    "kpId": "kp-1.6-04"
  },
  {
    "id": 796,
    "grade": 7,
    "unitId": 14,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 14: 进阶运算",
      "en": "Unit 14: Advanced Operations"
    },
    "title": {
      "zh": "开方还原",
      "en": "Root Restoration"
    },
    "topic": "Algebra",
    "kpId": "kp-1.7-02"
  },
  {
    "id": 797,
    "grade": 7,
    "unitId": 14,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 14: 进阶运算",
      "en": "Unit 14: Advanced Operations"
    },
    "title": {
      "zh": "天文数字",
      "en": "Astronomical Numbers"
    },
    "topic": "Algebra",
    "kpId": "kp-1.8-02"
  },
  {
    "id": 798,
    "grade": 7,
    "unitId": 15,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 15: 估算进阶",
      "en": "Unit 15: Advanced Estimation"
    },
    "title": {
      "zh": "截断术",
      "en": "Truncation Technique"
    },
    "topic": "Algebra",
    "kpId": "kp-1.9-03"
  },
  {
    "id": 799,
    "grade": 7,
    "unitId": 15,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 15: 估算进阶",
      "en": "Unit 15: Advanced Estimation"
    },
    "title": {
      "zh": "快速估算",
      "en": "Quick Estimation"
    },
    "topic": "Algebra",
    "kpId": "kp-1.9-04"
  },
  {
    "id": 800,
    "grade": 7,
    "unitId": 15,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 15: 估算进阶",
      "en": "Unit 15: Advanced Estimation"
    },
    "title": {
      "zh": "验算捉错",
      "en": "Check by Estimation"
    },
    "topic": "Algebra",
    "kpId": "kp-1.9-05"
  },
  {
    "id": 801,
    "grade": 7,
    "unitId": 15,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 15: 估算进阶",
      "en": "Unit 15: Advanced Estimation"
    },
    "title": {
      "zh": "目测长度",
      "en": "Estimating Lengths"
    },
    "topic": "Algebra",
    "kpId": "kp-1.9-06"
  },
  {
    "id": 802,
    "grade": 7,
    "unitId": 15,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 15: 估算进阶",
      "en": "Unit 15: Advanced Estimation"
    },
    "title": {
      "zh": "四舍五入争议",
      "en": "Rounding Dispute"
    },
    "topic": "Algebra",
    "kpId": "kp-1.9-07"
  },
  {
    "id": 803,
    "grade": 7,
    "unitId": 16,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 16: 比例进阶",
      "en": "Unit 16: Advanced Ratios"
    },
    "title": {
      "zh": "救援通道",
      "en": "Rescue Tunnel"
    },
    "topic": "Algebra",
    "kpId": "kp-1.11-03"
  },
  {
    "id": 804,
    "grade": 7,
    "unitId": 16,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 16: 比例进阶",
      "en": "Unit 16: Advanced Ratios"
    },
    "title": {
      "zh": "地图测距",
      "en": "Map Distance"
    },
    "topic": "Algebra",
    "kpId": "kp-1.11-04"
  },
  {
    "id": 805,
    "grade": 7,
    "unitId": 16,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 16: 比例进阶",
      "en": "Unit 16: Advanced Ratios"
    },
    "title": {
      "zh": "公平分金",
      "en": "Fair Gold Split"
    },
    "topic": "Algebra",
    "kpId": "kp-1.11-05"
  }
] as MissionSummary[];
