import type { MissionSummary } from '../../types';

// Auto-generated by scripts/generate-mission-summaries.ts
export const MISSION_SUMMARIES_Y8: MissionSummary[] = [
  {
    "id": 811,
    "grade": 8,
    "unitId": 1,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 1: 进军篇 · 虎牢关",
      "en": "Unit 1: The March · Hulao Pass"
    },
    "title": {
      "zh": "急行军",
      "en": "Forced March"
    },
    "topic": "Functions",
    "kpId": "kp-3.2-01"
  },
  {
    "id": 812,
    "grade": 8,
    "unitId": 1,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 1: 进军篇 · 虎牢关",
      "en": "Unit 1: The March · Hulao Pass"
    },
    "title": {
      "zh": "追击哨兵",
      "en": "Intercepting Scouts"
    },
    "topic": "Functions",
    "kpId": "kp-2.2-01"
  },
  {
    "id": 813,
    "grade": 8,
    "unitId": 1,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 1: 进军篇 · 虎牢关",
      "en": "Unit 1: The March · Hulao Pass"
    },
    "title": {
      "zh": "合围之势",
      "en": "Encirclement"
    },
    "topic": "Functions",
    "kpId": "kp-3.2-01"
  },
  {
    "id": 814,
    "grade": 8,
    "unitId": 1,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 1: 进军篇 · 虎牢关",
      "en": "Unit 1: The March · Hulao Pass"
    },
    "title": {
      "zh": "虎牢会合",
      "en": "Hulao Rendezvous"
    },
    "topic": "Functions",
    "kpId": "kp-2.2-01"
  },
  {
    "id": 821,
    "grade": 8,
    "unitId": 2,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 2: 攻城篇 · 虎牢关攻防",
      "en": "Unit 2: Siege · Hulao Pass Battle"
    },
    "title": {
      "zh": "城墙角度",
      "en": "Wall Angles"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-03"
  },
  {
    "id": 822,
    "grade": 8,
    "unitId": 2,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 2: 攻城篇 · 虎牢关攻防",
      "en": "Unit 2: Siege · Hulao Pass Battle"
    },
    "title": {
      "zh": "箭塔射角",
      "en": "Arrow Tower Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-03"
  },
  {
    "id": 823,
    "grade": 8,
    "unitId": 2,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 2: 攻城篇 · 虎牢关攻防",
      "en": "Unit 2: Siege · Hulao Pass Battle"
    },
    "title": {
      "zh": "攻城梯",
      "en": "Siege Ladder"
    },
    "topic": "Geometry",
    "kpId": "kp-6.1-01"
  },
  {
    "id": 824,
    "grade": 8,
    "unitId": 2,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 2: 攻城篇 · 虎牢关攻防",
      "en": "Unit 2: Siege · Hulao Pass Battle"
    },
    "title": {
      "zh": "吊桥长度",
      "en": "Drawbridge Length"
    },
    "topic": "Geometry",
    "kpId": "kp-6.1-01"
  },
  {
    "id": 831,
    "grade": 8,
    "unitId": 3,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 3: 营地篇 · 官渡之战前奏",
      "en": "Unit 3: Camp · Prelude to Guandu"
    },
    "title": {
      "zh": "安营扎寨",
      "en": "Setting Camp"
    },
    "topic": "Geometry",
    "kpId": "kp-5.2-01"
  },
  {
    "id": 832,
    "grade": 8,
    "unitId": 3,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 3: 营地篇 · 官渡之战前奏",
      "en": "Unit 3: Camp · Prelude to Guandu"
    },
    "title": {
      "zh": "点将台",
      "en": "Command Platform"
    },
    "topic": "Geometry",
    "kpId": "kp-5.2-01"
  },
  {
    "id": 833,
    "grade": 8,
    "unitId": 3,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 3: 营地篇 · 官渡之战前奏",
      "en": "Unit 3: Camp · Prelude to Guandu"
    },
    "title": {
      "zh": "圆形瞭望塔",
      "en": "Circular Watchtower"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-01"
  },
  {
    "id": 834,
    "grade": 8,
    "unitId": 3,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 3: 营地篇 · 官渡之战前奏",
      "en": "Unit 3: Camp · Prelude to Guandu"
    },
    "title": {
      "zh": "围栏长度",
      "en": "Fence Length"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-01"
  },
  {
    "id": 835,
    "grade": 8,
    "unitId": 3,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 3: 营地篇 · 官渡之战前奏",
      "en": "Unit 3: Camp · Prelude to Guandu"
    },
    "title": {
      "zh": "修筑粮仓",
      "en": "Building Granaries"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-01"
  },
  {
    "id": 841,
    "grade": 8,
    "unitId": 4,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 4: 治理篇 · 官渡胜后",
      "en": "Unit 4: Governance · Post-Guandu"
    },
    "title": {
      "zh": "征收粮税",
      "en": "Collecting Grain Tax"
    },
    "topic": "Algebra",
    "kpId": "kp-1.13-01"
  },
  {
    "id": 842,
    "grade": 8,
    "unitId": 4,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 4: 治理篇 · 官渡胜后",
      "en": "Unit 4: Governance · Post-Guandu"
    },
    "title": {
      "zh": "军备折扣",
      "en": "Armament Discount"
    },
    "topic": "Algebra",
    "kpId": "kp-1.13-01"
  },
  {
    "id": 843,
    "grade": 8,
    "unitId": 4,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 4: 治理篇 · 官渡胜后",
      "en": "Unit 4: Governance · Post-Guandu"
    },
    "title": {
      "zh": "军费放贷",
      "en": "Military Lending"
    },
    "topic": "Algebra",
    "kpId": "kp-1.13-01"
  },
  {
    "id": 851,
    "grade": 8,
    "unitId": 5,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 5: 情报篇 · 官渡谍报",
      "en": "Unit 5: Intelligence · Guandu Espionage"
    },
    "title": {
      "zh": "敌军平均兵力",
      "en": "Enemy Average Strength"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-01"
  },
  {
    "id": 852,
    "grade": 8,
    "unitId": 5,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 5: 情报篇 · 官渡谍报",
      "en": "Unit 5: Intelligence · Guandu Espionage"
    },
    "title": {
      "zh": "中位情报",
      "en": "Median Intelligence"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-01"
  },
  {
    "id": 853,
    "grade": 8,
    "unitId": 5,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 5: 情报篇 · 官渡谍报",
      "en": "Unit 5: Intelligence · Guandu Espionage"
    },
    "title": {
      "zh": "奇袭概率",
      "en": "Raid Probability"
    },
    "topic": "Statistics",
    "kpId": "kp-8.1-01"
  },
  {
    "id": 854,
    "grade": 8,
    "unitId": 5,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 5: 情报篇 · 官渡谍报",
      "en": "Unit 5: Intelligence · Guandu Espionage"
    },
    "title": {
      "zh": "双重情报",
      "en": "Double Intelligence"
    },
    "topic": "Statistics",
    "kpId": "kp-8.1-01"
  },
  {
    "id": 861,
    "grade": 8,
    "unitId": 6,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 隆中对前奏",
      "en": "Unit 6: Algebra · Prelude to Longzhong"
    },
    "title": {
      "zh": "兵力展开",
      "en": "Force Deployment"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-03"
  },
  {
    "id": 862,
    "grade": 8,
    "unitId": 6,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 隆中对前奏",
      "en": "Unit 6: Algebra · Prelude to Longzhong"
    },
    "title": {
      "zh": "粮草分配",
      "en": "Supply Distribution"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-03"
  },
  {
    "id": 863,
    "grade": 8,
    "unitId": 6,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 隆中对前奏",
      "en": "Unit 6: Algebra · Prelude to Longzhong"
    },
    "title": {
      "zh": "情报归纳",
      "en": "Intelligence Summary"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-05"
  },
  {
    "id": 864,
    "grade": 8,
    "unitId": 6,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 隆中对前奏",
      "en": "Unit 6: Algebra · Prelude to Longzhong"
    },
    "title": {
      "zh": "军令简化",
      "en": "Simplify Orders"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-05"
  },
  {
    "id": 865,
    "grade": 8,
    "unitId": 6,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 隆中对前奏",
      "en": "Unit 6: Algebra · Prelude to Longzhong"
    },
    "title": {
      "zh": "兵力限制",
      "en": "Troop Limit"
    },
    "topic": "Algebra",
    "kpId": "kp-2.6-01"
  },
  {
    "id": 866,
    "grade": 8,
    "unitId": 6,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 隆中对前奏",
      "en": "Unit 6: Algebra · Prelude to Longzhong"
    },
    "title": {
      "zh": "粮草底线",
      "en": "Supply Floor"
    },
    "topic": "Algebra",
    "kpId": "kp-2.6-01"
  },
  {
    "id": 871,
    "grade": 8,
    "unitId": 7,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 7: 图表篇 · 天下形势图",
      "en": "Unit 7: Charts · Map of the Realm"
    },
    "title": {
      "zh": "急行军速度",
      "en": "March Speed"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-01"
  },
  {
    "id": 872,
    "grade": 8,
    "unitId": 7,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 7: 图表篇 · 天下形势图",
      "en": "Unit 7: Charts · Map of the Realm"
    },
    "title": {
      "zh": "追击距离",
      "en": "Pursuit Distance"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-01"
  },
  {
    "id": 873,
    "grade": 8,
    "unitId": 7,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 7: 图表篇 · 天下形势图",
      "en": "Unit 7: Charts · Map of the Realm"
    },
    "title": {
      "zh": "天下兵力",
      "en": "Realm Forces"
    },
    "topic": "Algebra",
    "kpId": "kp-1.8-01"
  },
  {
    "id": 874,
    "grade": 8,
    "unitId": 7,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 7: 图表篇 · 天下形势图",
      "en": "Unit 7: Charts · Map of the Realm"
    },
    "title": {
      "zh": "粮草总量",
      "en": "Total Supplies"
    },
    "topic": "Algebra",
    "kpId": "kp-1.8-01"
  },
  {
    "id": 881,
    "grade": 8,
    "unitId": 8,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 8: 度量篇 · 荆州治理",
      "en": "Unit 8: Measure · Governing Jingzhou"
    },
    "title": {
      "zh": "税收路线",
      "en": "Tax Revenue Route"
    },
    "topic": "Functions",
    "kpId": "kp-3.2-01"
  },
  {
    "id": 882,
    "grade": 8,
    "unitId": 8,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 8: 度量篇 · 荆州治理",
      "en": "Unit 8: Measure · Governing Jingzhou"
    },
    "title": {
      "zh": "人口增长",
      "en": "Population Growth"
    },
    "topic": "Functions",
    "kpId": "kp-3.2-01"
  },
  {
    "id": 885,
    "grade": 8,
    "unitId": 5,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 5: 情报篇 · 官渡谍报",
      "en": "Unit 5: Intelligence · Guandu Espionage"
    },
    "title": {
      "zh": "粮草与兵力",
      "en": "Supplies & Forces"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-01"
  },
  {
    "id": 886,
    "grade": 8,
    "unitId": 5,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 5: 情报篇 · 官渡谍报",
      "en": "Unit 5: Intelligence · Guandu Espionage"
    },
    "title": {
      "zh": "情报交叉",
      "en": "Intelligence Crosscheck"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-01"
  },
  {
    "id": 887,
    "grade": 8,
    "unitId": 6,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 几何插曲",
      "en": "Unit 6: Algebra · Geometry Interlude"
    },
    "title": {
      "zh": "阵法镜像",
      "en": "Formation Mirror"
    },
    "topic": "Geometry",
    "kpId": "kp-4.5-01"
  },
  {
    "id": 888,
    "grade": 8,
    "unitId": 6,
    "order": 8,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 几何插曲",
      "en": "Unit 6: Algebra · Geometry Interlude"
    },
    "title": {
      "zh": "旋转阵法",
      "en": "Rotating Formation"
    },
    "topic": "Geometry",
    "kpId": "kp-4.5-01"
  },
  {
    "id": 891,
    "grade": 8,
    "unitId": 7,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 7: 图表篇 · 天下形势图",
      "en": "Unit 7: Charts · Map of the Realm"
    },
    "title": {
      "zh": "粮草正比例",
      "en": "Direct Proportion of Supplies"
    },
    "topic": "Algebra",
    "kpId": "kp-1.11-01"
  },
  {
    "id": 892,
    "grade": 8,
    "unitId": 7,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 7: 图表篇 · 天下形势图",
      "en": "Unit 7: Charts · Map of the Realm"
    },
    "title": {
      "zh": "兵粮反比例",
      "en": "Inverse Proportion of Rations"
    },
    "topic": "Algebra",
    "kpId": "kp-1.11-01"
  },
  {
    "id": 895,
    "grade": 8,
    "unitId": 8,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 8: 度量篇 · 荆州治理",
      "en": "Unit 8: Measure · Governing Jingzhou"
    },
    "title": {
      "zh": "税收分配",
      "en": "Tax Distribution"
    },
    "topic": "Statistics",
    "kpId": "kp-1.11-01"
  },
  {
    "id": 896,
    "grade": 8,
    "unitId": 8,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 8: 度量篇 · 荆州治理",
      "en": "Unit 8: Measure · Governing Jingzhou"
    },
    "title": {
      "zh": "行军时间",
      "en": "March Duration"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-01"
  },
  {
    "id": 898,
    "grade": 8,
    "unitId": 6,
    "order": 9,
    "unitTitle": {
      "zh": "Unit 6: 代数篇 · 隆中对前奏",
      "en": "Unit 6: Algebra · Prelude to Longzhong"
    },
    "title": {
      "zh": "负号突围",
      "en": "Negative Breakthrough"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-03"
  },
  {
    "id": 8901,
    "grade": 8,
    "unitId": 9,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 9: 指数进阶",
      "en": "Unit 9: Advanced Indices"
    },
    "title": {
      "zh": "合兵指数",
      "en": "Army Merger Index"
    },
    "topic": "Algebra",
    "kpId": "kp-2.4-01"
  },
  {
    "id": 8902,
    "grade": 8,
    "unitId": 9,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 9: 指数进阶",
      "en": "Unit 9: Advanced Indices"
    },
    "title": {
      "zh": "分兵开方",
      "en": "Root Division"
    },
    "topic": "Algebra",
    "kpId": "kp-2.4-02"
  },
  {
    "id": 8903,
    "grade": 8,
    "unitId": 9,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 9: 指数进阶",
      "en": "Unit 9: Advanced Indices"
    },
    "title": {
      "zh": "翻倍合幂",
      "en": "Double & Power Merge"
    },
    "topic": "Algebra",
    "kpId": "kp-2.4-03"
  },
  {
    "id": 8904,
    "grade": 8,
    "unitId": 10,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 10: 行军图解",
      "en": "Unit 10: March Diagrams"
    },
    "title": {
      "zh": "行军速度",
      "en": "March Speed"
    },
    "topic": "Functions",
    "kpId": "kp-2.9-01"
  },
  {
    "id": 8905,
    "grade": 8,
    "unitId": 10,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 10: 行军图解",
      "en": "Unit 10: March Diagrams"
    },
    "title": {
      "zh": "速度图积",
      "en": "Speed-Time Area"
    },
    "topic": "Functions",
    "kpId": "kp-2.9-02"
  },
  {
    "id": 8906,
    "grade": 8,
    "unitId": 10,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 10: 行军图解",
      "en": "Unit 10: March Diagrams"
    },
    "title": {
      "zh": "梯形行军",
      "en": "Trapezium March"
    },
    "topic": "Functions",
    "kpId": "kp-2.9-04"
  },
  {
    "id": 8907,
    "grade": 8,
    "unitId": 11,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 11: 尺规作图",
      "en": "Unit 11: Geometric Constructions"
    },
    "title": {
      "zh": "等边阵法",
      "en": "Equilateral Formation"
    },
    "topic": "Geometry",
    "kpId": "kp-4.2-02"
  },
  {
    "id": 8908,
    "grade": 8,
    "unitId": 11,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 11: 尺规作图",
      "en": "Unit 11: Geometric Constructions"
    },
    "title": {
      "zh": "角分兵线",
      "en": "Angle Bisector"
    },
    "topic": "Geometry",
    "kpId": "kp-4.2-03"
  },
  {
    "id": 8909,
    "grade": 8,
    "unitId": 12,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 12: 图表解读",
      "en": "Unit 12: Reading Charts"
    },
    "title": {
      "zh": "军粮饼图",
      "en": "Ration Pie Chart"
    },
    "topic": "Statistics",
    "kpId": "kp-9.4-01"
  },
  {
    "id": 8910,
    "grade": 8,
    "unitId": 12,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 12: 图表解读",
      "en": "Unit 12: Reading Charts"
    },
    "title": {
      "zh": "茎叶情报",
      "en": "Stem-and-Leaf Intel"
    },
    "topic": "Statistics",
    "kpId": "kp-9.4-02"
  },
  {
    "id": 8911,
    "grade": 8,
    "unitId": 12,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 12: 图表解读",
      "en": "Unit 12: Reading Charts"
    },
    "title": {
      "zh": "频率峰值",
      "en": "Frequency Peak"
    },
    "topic": "Statistics",
    "kpId": "kp-9.4-03"
  },
  {
    "id": 8912,
    "grade": 8,
    "unitId": 13,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 13: 代数入门进阶",
      "en": "Unit 13: Algebraic Expressions"
    },
    "title": {
      "zh": "药剂配方",
      "en": "Potion Formula"
    },
    "topic": "Algebra",
    "kpId": "kp-2.1-02"
  },
  {
    "id": 8913,
    "grade": 8,
    "unitId": 13,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 13: 代数入门进阶",
      "en": "Unit 13: Algebraic Expressions"
    },
    "title": {
      "zh": "双变量情报",
      "en": "Two-Variable Intel"
    },
    "topic": "Algebra",
    "kpId": "kp-2.1-03"
  },
  {
    "id": 8914,
    "grade": 8,
    "unitId": 14,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 14: 代数运算进阶",
      "en": "Unit 14: Advanced Algebra Operations"
    },
    "title": {
      "zh": "火攻展开",
      "en": "Fire Attack Expansion"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-04"
  },
  {
    "id": 8915,
    "grade": 8,
    "unitId": 14,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 14: 代数运算进阶",
      "en": "Unit 14: Advanced Algebra Operations"
    },
    "title": {
      "zh": "逆向拆解",
      "en": "Reverse Engineering"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-07"
  },
  {
    "id": 8916,
    "grade": 8,
    "unitId": 14,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 14: 代数运算进阶",
      "en": "Unit 14: Advanced Algebra Operations"
    },
    "title": {
      "zh": "高阶破译",
      "en": "Advanced Decryption"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-08"
  },
  {
    "id": 8917,
    "grade": 8,
    "unitId": 14,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 14: 代数运算进阶",
      "en": "Unit 14: Advanced Algebra Operations"
    },
    "title": {
      "zh": "化繁为简",
      "en": "Simplification"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-09"
  },
  {
    "id": 8918,
    "grade": 8,
    "unitId": 14,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 14: 代数运算进阶",
      "en": "Unit 14: Advanced Algebra Operations"
    },
    "title": {
      "zh": "合兵一处",
      "en": "Combining Forces"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-10"
  },
  {
    "id": 8919,
    "grade": 8,
    "unitId": 14,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 14: 代数运算进阶",
      "en": "Unit 14: Advanced Algebra Operations"
    },
    "title": {
      "zh": "分兵之谜",
      "en": "Division Paradox"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-11"
  },
  {
    "id": 8920,
    "grade": 8,
    "unitId": 14,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 14: 代数运算进阶",
      "en": "Unit 14: Advanced Algebra Operations"
    },
    "title": {
      "zh": "指数合击",
      "en": "Index Law Strike"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-12"
  },
  {
    "id": 8921,
    "grade": 8,
    "unitId": 14,
    "order": 8,
    "unitTitle": {
      "zh": "Unit 14: 代数运算进阶",
      "en": "Unit 14: Advanced Algebra Operations"
    },
    "title": {
      "zh": "完全平方",
      "en": "Completing the Square"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-13"
  },
  {
    "id": 8922,
    "grade": 8,
    "unitId": 15,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 15: 角度进阶",
      "en": "Unit 15: Advanced Angles"
    },
    "title": {
      "zh": "对顶侦察",
      "en": "Vertical Angle Recon"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-02"
  },
  {
    "id": 8923,
    "grade": 8,
    "unitId": 15,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 15: 角度进阶",
      "en": "Unit 15: Advanced Angles"
    },
    "title": {
      "zh": "四方城防",
      "en": "Quadrilateral Fortress"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-05"
  },
  {
    "id": 8924,
    "grade": 8,
    "unitId": 15,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 15: 角度进阶",
      "en": "Unit 15: Advanced Angles"
    },
    "title": {
      "zh": "十面埋伏",
      "en": "Decagon Ambush"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-07"
  },
  {
    "id": 8925,
    "grade": 8,
    "unitId": 15,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 15: 角度进阶",
      "en": "Unit 15: Advanced Angles"
    },
    "title": {
      "zh": "逆推边数",
      "en": "Reverse Polygon"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-08"
  },
  {
    "id": 8926,
    "grade": 8,
    "unitId": 15,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 15: 角度进阶",
      "en": "Unit 15: Advanced Angles"
    },
    "title": {
      "zh": "直线攻防",
      "en": "Straight Line Defense"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-09"
  },
  {
    "id": 8927,
    "grade": 8,
    "unitId": 15,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 15: 角度进阶",
      "en": "Unit 15: Advanced Angles"
    },
    "title": {
      "zh": "蜂巢阵",
      "en": "Hexagonal Formation"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-10"
  },
  {
    "id": 8928,
    "grade": 8,
    "unitId": 16,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 16: 图表与概率补充",
      "en": "Unit 16: Charts & Probability Supplement"
    },
    "title": {
      "zh": "军饷饼图",
      "en": "Pay Distribution Pie Chart"
    },
    "topic": "Statistics",
    "kpId": "kp-9.4-04"
  },
  {
    "id": 8929,
    "grade": 8,
    "unitId": 16,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 16: 图表与概率补充",
      "en": "Unit 16: Charts & Probability Supplement"
    },
    "title": {
      "zh": "军粮复利",
      "en": "Compound Rations"
    },
    "topic": "Algebra",
    "kpId": "kp-1.16-03"
  },
  {
    "id": 8930,
    "grade": 8,
    "unitId": 16,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 16: 图表与概率补充",
      "en": "Unit 16: Charts & Probability Supplement"
    },
    "title": {
      "zh": "实战频率",
      "en": "Experimental Frequency"
    },
    "topic": "Statistics",
    "kpId": "kp-8.2-02"
  },
  {
    "id": 8931,
    "grade": 8,
    "unitId": 17,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 17: 几何术语",
      "en": "Unit 17: Geometric Terms"
    },
    "title": {
      "zh": "辨形识敌",
      "en": "Shape Recognition"
    },
    "topic": "Geometry",
    "kpId": "kp-4.1-01"
  },
  {
    "id": 8932,
    "grade": 8,
    "unitId": 17,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 17: 几何术语",
      "en": "Unit 17: Geometric Terms"
    },
    "title": {
      "zh": "阵形辨别",
      "en": "Formation Properties"
    },
    "topic": "Geometry",
    "kpId": "kp-4.1-03"
  },
  {
    "id": 8933,
    "grade": 8,
    "unitId": 17,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 17: 几何术语",
      "en": "Unit 17: Geometric Terms"
    },
    "title": {
      "zh": "尺规营寨",
      "en": "Compass Fortress"
    },
    "topic": "Geometry",
    "kpId": "kp-4.2-01"
  },
  {
    "id": 8934,
    "grade": 8,
    "unitId": 17,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 17: 几何术语",
      "en": "Unit 17: Geometric Terms"
    },
    "title": {
      "zh": "轨迹侦察",
      "en": "Locus Patrol"
    },
    "topic": "Geometry",
    "kpId": "kp-4.2-04"
  },
  {
    "id": 8935,
    "grade": 8,
    "unitId": 18,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 18: 数据可视化",
      "en": "Unit 18: Data Visualisation"
    },
    "title": {
      "zh": "茎叶解码",
      "en": "Stem-and-Leaf Decode"
    },
    "topic": "Statistics",
    "kpId": "kp-9.4-05"
  },
  {
    "id": 8936,
    "grade": 8,
    "unitId": 18,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 18: 数据可视化",
      "en": "Unit 18: Data Visualisation"
    },
    "title": {
      "zh": "汇率情报",
      "en": "Exchange Rate Intelligence"
    },
    "topic": "Algebra",
    "kpId": "kp-2.9-03"
  },
  {
    "id": 8937,
    "grade": 8,
    "unitId": 18,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 18: 数据可视化",
      "en": "Unit 18: Data Visualisation"
    },
    "title": {
      "zh": "行军加速",
      "en": "March Acceleration"
    },
    "topic": "Algebra",
    "kpId": "kp-2.9-05"
  }
] as MissionSummary[];
