import type { MissionSummary } from '../../types';

// Auto-generated by scripts/generate-mission-summaries.ts
export const MISSION_SUMMARIES_Y9: MissionSummary[] = [
  {
    "id": 911,
    "grade": 9,
    "unitId": 1,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 1: 粮草与指数定律",
      "en": "Unit 1: Supplies & Indices"
    },
    "title": {
      "zh": "官渡积粮",
      "en": "Guandu Supplies"
    },
    "topic": "Algebra",
    "kpId": "kp-1.7-01"
  },
  {
    "id": 912,
    "grade": 9,
    "unitId": 1,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 1: 粮草与指数定律",
      "en": "Unit 1: Supplies & Indices"
    },
    "title": {
      "zh": "粮仓扩建",
      "en": "Granary Expansion"
    },
    "topic": "Algebra",
    "kpId": "kp-1.7-01"
  },
  {
    "id": 913,
    "grade": 9,
    "unitId": 1,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 1: 粮草与指数定律",
      "en": "Unit 1: Supplies & Indices"
    },
    "title": {
      "zh": "火烧乌巢",
      "en": "Burning Wuchao"
    },
    "topic": "Algebra",
    "kpId": "kp-1.7-01"
  },
  {
    "id": 921,
    "grade": 9,
    "unitId": 2,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 2: 攻城与勾股定理",
      "en": "Unit 2: Siege & Pythagoras"
    },
    "title": {
      "zh": "云梯攻城",
      "en": "Siege Ladders"
    },
    "topic": "Geometry",
    "kpId": "kp-6.1-01"
  },
  {
    "id": 922,
    "grade": 9,
    "unitId": 2,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 2: 攻城与勾股定理",
      "en": "Unit 2: Siege & Pythagoras"
    },
    "title": {
      "zh": "望楼侦察",
      "en": "Scouting from the Tower"
    },
    "topic": "Geometry",
    "kpId": "kp-6.2-01"
  },
  {
    "id": 923,
    "grade": 9,
    "unitId": 2,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 2: 攻城与勾股定理",
      "en": "Unit 2: Siege & Pythagoras"
    },
    "title": {
      "zh": "地道突袭",
      "en": "Tunnel Raid"
    },
    "topic": "Geometry",
    "kpId": "kp-6.1-01"
  },
  {
    "id": 931,
    "grade": 9,
    "unitId": 3,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 3: 阵法与相似",
      "en": "Unit 3: Formations & Similarity"
    },
    "title": {
      "zh": "旗帜缩放",
      "en": "Flag Scaling"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-01"
  },
  {
    "id": 932,
    "grade": 9,
    "unitId": 3,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 3: 阵法与相似",
      "en": "Unit 3: Formations & Similarity"
    },
    "title": {
      "zh": "地图测绘",
      "en": "Map Surveying"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-01"
  },
  {
    "id": 933,
    "grade": 9,
    "unitId": 3,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 3: 阵法与相似",
      "en": "Unit 3: Formations & Similarity"
    },
    "title": {
      "zh": "影子量旗",
      "en": "Shadow Flagpole"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-01"
  },
  {
    "id": 934,
    "grade": 9,
    "unitId": 3,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 3: 阵法与相似",
      "en": "Unit 3: Formations & Similarity"
    },
    "title": {
      "zh": "塔楼测高",
      "en": "Tower Height"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-01"
  },
  {
    "id": 941,
    "grade": 9,
    "unitId": 4,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 4: 军备与比率",
      "en": "Unit 4: Armaments & Ratio"
    },
    "title": {
      "zh": "兵粮配给",
      "en": "Rationing"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-01"
  },
  {
    "id": 942,
    "grade": 9,
    "unitId": 4,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 4: 军备与比率",
      "en": "Unit 4: Armaments & Ratio"
    },
    "title": {
      "zh": "混合阵法",
      "en": "Mixed Formation"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-01"
  },
  {
    "id": 951,
    "grade": 9,
    "unitId": 5,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 5: 密探坐标·情报网",
      "en": "Unit 5: Spy Coordinates — Intelligence Network"
    },
    "title": {
      "zh": "官渡暗桩",
      "en": "Guandu Spy Posts"
    },
    "topic": "Geometry",
    "kpId": "kp-3.1-01"
  },
  {
    "id": 952,
    "grade": 9,
    "unitId": 5,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 5: 密探坐标·情报网",
      "en": "Unit 5: Spy Coordinates — Intelligence Network"
    },
    "title": {
      "zh": "密道斜率",
      "en": "Secret Tunnel Gradient"
    },
    "topic": "Algebra",
    "kpId": "kp-3.3-01"
  },
  {
    "id": 953,
    "grade": 9,
    "unitId": 5,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 5: 密探坐标·情报网",
      "en": "Unit 5: Spy Coordinates — Intelligence Network"
    },
    "title": {
      "zh": "撤退路线",
      "en": "Escape Route Equation"
    },
    "topic": "Algebra",
    "kpId": "kp-3.5-01"
  },
  {
    "id": 961,
    "grade": 9,
    "unitId": 6,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 6: 斜率密信·平行渗透",
      "en": "Unit 6: Gradient Cipher — Parallel Infiltration"
    },
    "title": {
      "zh": "平行密道",
      "en": "Parallel Tunnels"
    },
    "topic": "Algebra",
    "kpId": "kp-3.3-02"
  },
  {
    "id": 962,
    "grade": 9,
    "unitId": 6,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 6: 斜率密信·平行渗透",
      "en": "Unit 6: Gradient Cipher — Parallel Infiltration"
    },
    "title": {
      "zh": "补给起点",
      "en": "Supply Origin"
    },
    "topic": "Algebra",
    "kpId": "kp-3.5-02"
  },
  {
    "id": 963,
    "grade": 9,
    "unitId": 6,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 6: 斜率密信·平行渗透",
      "en": "Unit 6: Gradient Cipher — Parallel Infiltration"
    },
    "title": {
      "zh": "会合点",
      "en": "Rendezvous Point"
    },
    "topic": "Geometry",
    "kpId": "kp-3.4-01"
  },
  {
    "id": 971,
    "grade": 9,
    "unitId": 7,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 7: 铁匠铺·代数锻造",
      "en": "Unit 7: Blacksmith's Forge — Algebraic Forging"
    },
    "title": {
      "zh": "批量锻兵",
      "en": "Mass Forging"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-01"
  },
  {
    "id": 972,
    "grade": 9,
    "unitId": 7,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 7: 铁匠铺·代数锻造",
      "en": "Unit 7: Blacksmith's Forge — Algebraic Forging"
    },
    "title": {
      "zh": "军需打包",
      "en": "Supply Bundling"
    },
    "topic": "Algebra",
    "kpId": "kp-2.2-06"
  },
  {
    "id": 973,
    "grade": 9,
    "unitId": 7,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 7: 铁匠铺·代数锻造",
      "en": "Unit 7: Blacksmith's Forge — Algebraic Forging"
    },
    "title": {
      "zh": "粮草底线",
      "en": "Supply Minimum"
    },
    "topic": "Algebra",
    "kpId": "kp-2.6-01"
  },
  {
    "id": 974,
    "grade": 9,
    "unitId": 7,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 7: 铁匠铺·代数锻造",
      "en": "Unit 7: Blacksmith's Forge — Algebraic Forging"
    },
    "title": {
      "zh": "百万雄师",
      "en": "Million-Strong Army"
    },
    "topic": "Algebra",
    "kpId": "kp-1.8-01"
  },
  {
    "id": 981,
    "grade": 9,
    "unitId": 8,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 8: 阵前角度·平行线",
      "en": "Unit 8: Battle Angles — Parallel Lines"
    },
    "title": {
      "zh": "阵前角度",
      "en": "Formation Angles"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-01"
  },
  {
    "id": 982,
    "grade": 9,
    "unitId": 8,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 8: 阵前角度·平行线",
      "en": "Unit 8: Battle Angles — Parallel Lines"
    },
    "title": {
      "zh": "壕沟截角",
      "en": "Trench Angles"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-04"
  },
  {
    "id": 983,
    "grade": 9,
    "unitId": 8,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 8: 阵前角度·平行线",
      "en": "Unit 8: Battle Angles — Parallel Lines"
    },
    "title": {
      "zh": "堡垒内角",
      "en": "Fortress Interior Angles"
    },
    "topic": "Geometry",
    "kpId": "kp-4.6-06"
  },
  {
    "id": 991,
    "grade": 9,
    "unitId": 9,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 9: 行军速算·百分之道",
      "en": "Unit 9: March Speed — Way of Percentages"
    },
    "title": {
      "zh": "行军速度",
      "en": "March Speed"
    },
    "topic": "Algebra",
    "kpId": "kp-1.12-02"
  },
  {
    "id": 992,
    "grade": 9,
    "unitId": 9,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 9: 行军速算·百分之道",
      "en": "Unit 9: March Speed — Way of Percentages"
    },
    "title": {
      "zh": "兵力增长",
      "en": "Army Growth"
    },
    "topic": "Algebra",
    "kpId": "kp-1.13-02"
  },
  {
    "id": 993,
    "grade": 9,
    "unitId": 9,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 9: 行军速算·百分之道",
      "en": "Unit 9: March Speed — Way of Percentages"
    },
    "title": {
      "zh": "军饷原价",
      "en": "Original Stipend"
    },
    "topic": "Algebra",
    "kpId": "kp-1.13-04"
  },
  {
    "id": 9101,
    "grade": 9,
    "unitId": 10,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 10: 荆州屯田·度量篇",
      "en": "Unit 10: Jingzhou Fields — Mensuration"
    },
    "title": {
      "zh": "梯形田亩",
      "en": "Trapezium Fields"
    },
    "topic": "Geometry",
    "kpId": "kp-5.2-03"
  },
  {
    "id": 9102,
    "grade": 9,
    "unitId": 10,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 10: 荆州屯田·度量篇",
      "en": "Unit 10: Jingzhou Fields — Mensuration"
    },
    "title": {
      "zh": "圆形粮仓",
      "en": "Circular Granary"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-01"
  },
  {
    "id": 9103,
    "grade": 9,
    "unitId": 10,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 10: 荆州屯田·度量篇",
      "en": "Unit 10: Jingzhou Fields — Mensuration"
    },
    "title": {
      "zh": "粮仓容量",
      "en": "Granary Volume"
    },
    "topic": "Geometry",
    "kpId": "kp-5.4-01"
  },
  {
    "id": 9111,
    "grade": 9,
    "unitId": 11,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 11: 赤壁前夜·三角篇",
      "en": "Unit 11: Eve of Red Cliffs — Trigonometry"
    },
    "title": {
      "zh": "瞭望测距",
      "en": "Watchtower Range"
    },
    "topic": "Geometry",
    "kpId": "kp-6.1-01"
  },
  {
    "id": 9112,
    "grade": 9,
    "unitId": 11,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 11: 赤壁前夜·三角篇",
      "en": "Unit 11: Eve of Red Cliffs — Trigonometry"
    },
    "title": {
      "zh": "火箭射角",
      "en": "Fire Arrow Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-6.1-02"
  },
  {
    "id": 9113,
    "grade": 9,
    "unitId": 11,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 11: 赤壁前夜·三角篇",
      "en": "Unit 11: Eve of Red Cliffs — Trigonometry"
    },
    "title": {
      "zh": "连环船锁链",
      "en": "Chain Link Angle"
    },
    "topic": "Geometry",
    "kpId": "kp-6.1-02"
  },
  {
    "id": 9121,
    "grade": 9,
    "unitId": 12,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 12: 战后清点·统计篇",
      "en": "Unit 12: Post-battle Census — Statistics"
    },
    "title": {
      "zh": "伤亡均值",
      "en": "Casualty Mean"
    },
    "topic": "Statistics",
    "kpId": "kp-9.1-01"
  },
  {
    "id": 9122,
    "grade": 9,
    "unitId": 12,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 12: 战后清点·统计篇",
      "en": "Unit 12: Post-battle Census — Statistics"
    },
    "title": {
      "zh": "物资中位数",
      "en": "Supply Median"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-02"
  },
  {
    "id": 9123,
    "grade": 9,
    "unitId": 12,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 12: 战后清点·统计篇",
      "en": "Unit 12: Post-battle Census — Statistics"
    },
    "title": {
      "zh": "援军概率",
      "en": "Reinforcement Probability"
    },
    "topic": "Statistics",
    "kpId": "kp-8.1-01"
  },
  {
    "id": 9131,
    "grade": 9,
    "unitId": 13,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 13: 赤壁前奏·高等代数",
      "en": "Unit 13: Red Cliffs Prelude — Advanced Algebra"
    },
    "title": {
      "zh": "粮草密约",
      "en": "Secret Supply Pact"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-01"
  },
  {
    "id": 9132,
    "grade": 9,
    "unitId": 13,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 13: 赤壁前奏·高等代数",
      "en": "Unit 13: Red Cliffs Prelude — Advanced Algebra"
    },
    "title": {
      "zh": "投石轨迹",
      "en": "Catapult Trajectory"
    },
    "topic": "Algebra",
    "kpId": "kp-2.10-01"
  },
  {
    "id": 9141,
    "grade": 9,
    "unitId": 14,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "谍报交集",
      "en": "Intelligence Overlap"
    },
    "topic": "Statistics",
    "kpId": "kp-8.1-01"
  },
  {
    "id": 9142,
    "grade": 9,
    "unitId": 14,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "烽火扇面",
      "en": "Beacon Arc"
    },
    "topic": "Geometry",
    "kpId": "kp-5.3-01"
  },
  {
    "id": 9143,
    "grade": 9,
    "unitId": 14,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "阵型旋转",
      "en": "Formation Rotation"
    },
    "topic": "Geometry",
    "kpId": "kp-7.2-01"
  },
  {
    "id": 9144,
    "grade": 9,
    "unitId": 14,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "战旗放大",
      "en": "Banner Enlargement"
    },
    "topic": "Geometry",
    "kpId": "kp-7.3-01"
  },
  {
    "id": 9145,
    "grade": 9,
    "unitId": 14,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "东风向量",
      "en": "East Wind Vector"
    },
    "topic": "Geometry",
    "kpId": "kp-7.2-01"
  },
  {
    "id": 9146,
    "grade": 9,
    "unitId": 14,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "伤亡频率",
      "en": "Casualty Frequency"
    },
    "topic": "Statistics",
    "kpId": "kp-9.1-01"
  },
  {
    "id": 9147,
    "grade": 9,
    "unitId": 14,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "二阶兵符",
      "en": "Two-Stage Token"
    },
    "topic": "Statistics",
    "kpId": "kp-9.2-01"
  },
  {
    "id": 9148,
    "grade": 9,
    "unitId": 14,
    "order": 8,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "不放回抽签",
      "en": "Draw Without Replacement"
    },
    "topic": "Statistics",
    "kpId": "kp-9.2-02"
  },
  {
    "id": 9149,
    "grade": 9,
    "unitId": 14,
    "order": 9,
    "unitTitle": {
      "zh": "Unit 14: 赤壁前奏·数据与变换",
      "en": "Unit 14: Red Cliffs Prelude — Data & Transformations"
    },
    "title": {
      "zh": "颜色配对",
      "en": "Colour Pairs"
    },
    "topic": "Statistics",
    "kpId": "kp-9.2-02"
  },
  {
    "id": 9151,
    "grade": 9,
    "unitId": 15,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 15: 平行线方程",
      "en": "Unit 15: Parallel Line Equations"
    },
    "title": {
      "zh": "平行防线",
      "en": "Parallel Defences"
    },
    "topic": "Algebra",
    "kpId": "kp-3.6-01"
  },
  {
    "id": 9152,
    "grade": 9,
    "unitId": 15,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 15: 平行线方程",
      "en": "Unit 15: Parallel Line Equations"
    },
    "title": {
      "zh": "建造平行防线",
      "en": "Build Parallel Defence"
    },
    "topic": "Algebra",
    "kpId": "kp-3.6-02"
  },
  {
    "id": 9153,
    "grade": 9,
    "unitId": 16,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 16: 组合图形",
      "en": "Unit 16: Compound Shapes"
    },
    "title": {
      "zh": "L形阵地",
      "en": "L-Shaped Fortification"
    },
    "topic": "Geometry",
    "kpId": "kp-5.5-01"
  },
  {
    "id": 9154,
    "grade": 9,
    "unitId": 16,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 16: 组合图形",
      "en": "Unit 16: Compound Shapes"
    },
    "title": {
      "zh": "缺口城墙",
      "en": "Notched Wall"
    },
    "topic": "Geometry",
    "kpId": "kp-5.5-03"
  },
  {
    "id": 9155,
    "grade": 9,
    "unitId": 17,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 17: 散点图",
      "en": "Unit 17: Scatter Diagrams"
    },
    "title": {
      "zh": "军情散点",
      "en": "Intelligence Scatter"
    },
    "topic": "Statistics",
    "kpId": "kp-9.5-01"
  },
  {
    "id": 9156,
    "grade": 9,
    "unitId": 17,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 17: 散点图",
      "en": "Unit 17: Scatter Diagrams"
    },
    "title": {
      "zh": "拟合斜率",
      "en": "Best Fit Gradient"
    },
    "topic": "Statistics",
    "kpId": "kp-9.5-03"
  },
  {
    "id": 9157,
    "grade": 9,
    "unitId": 17,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 17: 散点图",
      "en": "Unit 17: Scatter Diagrams"
    },
    "title": {
      "zh": "内插外推",
      "en": "Interpolation vs Extrapolation"
    },
    "topic": "Statistics",
    "kpId": "kp-9.5-04"
  },
  {
    "id": 9161,
    "grade": 9,
    "unitId": 18,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "破括号",
      "en": "Breaking Brackets"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-03"
  },
  {
    "id": 9162,
    "grade": 9,
    "unitId": 18,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "两军对峙",
      "en": "Unknowns on Both Sides"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-04"
  },
  {
    "id": 9163,
    "grade": 9,
    "unitId": 18,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "列方程",
      "en": "Setting Up Equations"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-05"
  },
  {
    "id": 9164,
    "grade": 9,
    "unitId": 18,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "城墙周长",
      "en": "Forming & Solving"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-06"
  },
  {
    "id": 9165,
    "grade": 9,
    "unitId": 18,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "试错逼近",
      "en": "Trial & Improvement"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-07"
  },
  {
    "id": 9166,
    "grade": 9,
    "unitId": 18,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "因式分解求根",
      "en": "Factoring Quadratics"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-09"
  },
  {
    "id": 9167,
    "grade": 9,
    "unitId": 18,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "万能公式",
      "en": "Quadratic Formula"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-10"
  },
  {
    "id": 9168,
    "grade": 9,
    "unitId": 18,
    "order": 8,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "配方术",
      "en": "Completing the Square"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-11"
  },
  {
    "id": 9169,
    "grade": 9,
    "unitId": 18,
    "order": 9,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "双线夹击",
      "en": "Simultaneous Linear"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-12"
  },
  {
    "id": 9170,
    "grade": 9,
    "unitId": 18,
    "order": 10,
    "unitTitle": {
      "zh": "Unit 18: 方程进阶",
      "en": "Unit 18: Advanced Equations"
    },
    "title": {
      "zh": "线圆交锋",
      "en": "Linear-Quadratic Simultaneous"
    },
    "topic": "Algebra",
    "kpId": "kp-2.5-13"
  },
  {
    "id": 9171,
    "grade": 9,
    "unitId": 19,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 19: 变换进阶",
      "en": "Unit 19: Advanced Transformations"
    },
    "title": {
      "zh": "平移术",
      "en": "Translation"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-02"
  },
  {
    "id": 9172,
    "grade": 9,
    "unitId": 19,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 19: 变换进阶",
      "en": "Unit 19: Advanced Transformations"
    },
    "title": {
      "zh": "x轴镜像",
      "en": "Reflection in x-axis"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-04"
  },
  {
    "id": 9173,
    "grade": 9,
    "unitId": 19,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 19: 变换进阶",
      "en": "Unit 19: Advanced Transformations"
    },
    "title": {
      "zh": "y=x镜像",
      "en": "Reflection in y=x"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-06"
  },
  {
    "id": 9174,
    "grade": 9,
    "unitId": 19,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 19: 变换进阶",
      "en": "Unit 19: Advanced Transformations"
    },
    "title": {
      "zh": "逆时针90°",
      "en": "Rotation 90° CCW"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-08"
  },
  {
    "id": 9175,
    "grade": 9,
    "unitId": 19,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 19: 变换进阶",
      "en": "Unit 19: Advanced Transformations"
    },
    "title": {
      "zh": "180°旋转",
      "en": "Rotation 180°"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-09"
  },
  {
    "id": 9176,
    "grade": 9,
    "unitId": 19,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 19: 变换进阶",
      "en": "Unit 19: Advanced Transformations"
    },
    "title": {
      "zh": "放大2倍",
      "en": "Enlargement SF 2"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-10"
  },
  {
    "id": 9177,
    "grade": 9,
    "unitId": 19,
    "order": 7,
    "unitTitle": {
      "zh": "Unit 19: 变换进阶",
      "en": "Unit 19: Advanced Transformations"
    },
    "title": {
      "zh": "缩小一半",
      "en": "Enlargement SF 1/2"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-11"
  },
  {
    "id": 9178,
    "grade": 9,
    "unitId": 19,
    "order": 8,
    "unitTitle": {
      "zh": "Unit 19: 变换进阶",
      "en": "Unit 19: Advanced Transformations"
    },
    "title": {
      "zh": "组合变换",
      "en": "Combined Transformations"
    },
    "topic": "Geometry",
    "kpId": "kp-7.1-12"
  },
  {
    "id": 9179,
    "grade": 9,
    "unitId": 20,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 20: 数据与统计补充",
      "en": "Unit 20: Data & Statistics Supplement"
    },
    "title": {
      "zh": "数据分类",
      "en": "Data Classification"
    },
    "topic": "Statistics",
    "kpId": "kp-9.1-02"
  },
  {
    "id": 9180,
    "grade": 9,
    "unitId": 20,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 20: 数据与统计补充",
      "en": "Unit 20: Data & Statistics Supplement"
    },
    "title": {
      "zh": "选择平均数",
      "en": "Choosing the Average"
    },
    "topic": "Statistics",
    "kpId": "kp-9.3-06"
  },
  {
    "id": 9181,
    "grade": 9,
    "unitId": 21,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 21: 代数分式",
      "en": "Unit 21: Algebraic Fractions"
    },
    "title": {
      "zh": "分式化简",
      "en": "Simplifying Algebraic Fractions"
    },
    "topic": "Algebra",
    "kpId": "kp-2.3-02"
  },
  {
    "id": 9182,
    "grade": 9,
    "unitId": 21,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 21: 代数分式",
      "en": "Unit 21: Algebraic Fractions"
    },
    "title": {
      "zh": "分式乘法",
      "en": "Fraction Multiplication"
    },
    "topic": "Algebra",
    "kpId": "kp-2.3-04"
  },
  {
    "id": 9183,
    "grade": 9,
    "unitId": 22,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 22: 数列进阶",
      "en": "Unit 22: Sequences — Advanced"
    },
    "title": {
      "zh": "等比公比",
      "en": "Geometric Common Ratio"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-04"
  },
  {
    "id": 9184,
    "grade": 9,
    "unitId": 22,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 22: 数列进阶",
      "en": "Unit 22: Sequences — Advanced"
    },
    "title": {
      "zh": "等比通项",
      "en": "Geometric nth Term"
    },
    "topic": "Algebra",
    "kpId": "kp-2.7-05"
  },
  {
    "id": 9185,
    "grade": 9,
    "unitId": 23,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 23: 坐标几何进阶",
      "en": "Unit 23: Coordinate Geometry — Advanced"
    },
    "title": {
      "zh": "两点距离",
      "en": "Distance Between Two Points"
    },
    "topic": "Geometry",
    "kpId": "kp-3.4-03"
  },
  {
    "id": 9186,
    "grade": 9,
    "unitId": 23,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 23: 坐标几何进阶",
      "en": "Unit 23: Coordinate Geometry — Advanced"
    },
    "title": {
      "zh": "中点坐标",
      "en": "Midpoint Coordinates"
    },
    "topic": "Geometry",
    "kpId": "kp-3.4-04"
  },
  {
    "id": 9187,
    "grade": 9,
    "unitId": 23,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 23: 坐标几何进阶",
      "en": "Unit 23: Coordinate Geometry — Advanced"
    },
    "title": {
      "zh": "求直线方程",
      "en": "Finding Line Equation"
    },
    "topic": "Algebra",
    "kpId": "kp-3.5-03"
  },
  {
    "id": 9188,
    "grade": 9,
    "unitId": 23,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 23: 坐标几何进阶",
      "en": "Unit 23: Coordinate Geometry — Advanced"
    },
    "title": {
      "zh": "直线交点",
      "en": "Line Intersection"
    },
    "topic": "Algebra",
    "kpId": "kp-3.5-04"
  },
  {
    "id": 9189,
    "grade": 9,
    "unitId": 24,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 24: 方位角",
      "en": "Unit 24: Bearings"
    },
    "title": {
      "zh": "方位角计算",
      "en": "Bearing Calculation"
    },
    "topic": "Geometry",
    "kpId": "kp-4.3-03"
  },
  {
    "id": 9190,
    "grade": 9,
    "unitId": 25,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 25: 相似全等进阶",
      "en": "Unit 25: Similarity & Congruence — Advanced"
    },
    "title": {
      "zh": "面积比",
      "en": "Area Ratio"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-03"
  },
  {
    "id": 9191,
    "grade": 9,
    "unitId": 25,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 25: 相似全等进阶",
      "en": "Unit 25: Similarity & Congruence — Advanced"
    },
    "title": {
      "zh": "体积比",
      "en": "Volume Ratio"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-04"
  },
  {
    "id": 9192,
    "grade": 9,
    "unitId": 25,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 25: 相似全等进阶",
      "en": "Unit 25: Similarity & Congruence — Advanced"
    },
    "title": {
      "zh": "相似三角形求边",
      "en": "Similar Triangles — Find Side"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-05"
  },
  {
    "id": 9193,
    "grade": 9,
    "unitId": 25,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 25: 相似全等进阶",
      "en": "Unit 25: Similarity & Congruence — Advanced"
    },
    "title": {
      "zh": "AAA能否证全等",
      "en": "Can AAA Prove Congruence?"
    },
    "topic": "Geometry",
    "kpId": "kp-4.4-06"
  },
  {
    "id": 9194,
    "grade": 9,
    "unitId": 26,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 26: 概率进阶",
      "en": "Unit 26: Probability — Advanced"
    },
    "title": {
      "zh": "基本概率",
      "en": "Basic Probability"
    },
    "topic": "Statistics",
    "kpId": "kp-8.3-01"
  },
  {
    "id": 9195,
    "grade": 9,
    "unitId": 26,
    "order": 2,
    "unitTitle": {
      "zh": "Unit 26: 概率进阶",
      "en": "Unit 26: Probability — Advanced"
    },
    "title": {
      "zh": "独立事件",
      "en": "Independent Events"
    },
    "topic": "Statistics",
    "kpId": "kp-8.3-04"
  },
  {
    "id": 9196,
    "grade": 9,
    "unitId": 26,
    "order": 3,
    "unitTitle": {
      "zh": "Unit 26: 概率进阶",
      "en": "Unit 26: Probability — Advanced"
    },
    "title": {
      "zh": "补事件",
      "en": "Complementary Events"
    },
    "topic": "Statistics",
    "kpId": "kp-8.3-05"
  },
  {
    "id": 9197,
    "grade": 9,
    "unitId": 26,
    "order": 4,
    "unitTitle": {
      "zh": "Unit 26: 概率进阶",
      "en": "Unit 26: Probability — Advanced"
    },
    "title": {
      "zh": "骰子组合",
      "en": "Dice Combinations"
    },
    "topic": "Statistics",
    "kpId": "kp-8.3-06"
  },
  {
    "id": 9198,
    "grade": 9,
    "unitId": 26,
    "order": 5,
    "unitTitle": {
      "zh": "Unit 26: 概率进阶",
      "en": "Unit 26: Probability — Advanced"
    },
    "title": {
      "zh": "互斥事件",
      "en": "Mutually Exclusive Events"
    },
    "topic": "Statistics",
    "kpId": "kp-8.3-07"
  },
  {
    "id": 9199,
    "grade": 9,
    "unitId": 26,
    "order": 6,
    "unitTitle": {
      "zh": "Unit 26: 概率进阶",
      "en": "Unit 26: Probability — Advanced"
    },
    "title": {
      "zh": "互斥加法",
      "en": "Addition Rule for Mutually Exclusive"
    },
    "topic": "Statistics",
    "kpId": "kp-8.3-08"
  },
  {
    "id": 9200,
    "grade": 9,
    "unitId": 27,
    "order": 1,
    "unitTitle": {
      "zh": "Unit 27: 统计补充",
      "en": "Unit 27: Statistics Supplement"
    },
    "title": {
      "zh": "三种平均数比较",
      "en": "Comparing Three Averages"
    },
    "topic": "Statistics",
    "kpId": "kp-9.2-03"
  }
] as MissionSummary[];
