/**
 * ClassWeeklyReport — One-click weekly report for grade leader / teacher.
 * Generates plain-text summary, copyable to WeChat/email.
 */
import { useState, useMemo } from 'react';
import { FileText, Copy, Check, X } from 'lucide-react';
import type { Language } from '../../types';
import type { StudentRow } from './types';
import { toTraditional } from '../../i18n/zhHantMap';

type Props = {
  lang: Language;
  grade: number;
  filterTag: string;
  students: StudentRow[];
  onClose: () => void;
};

export function ClassWeeklyReport({ lang, grade, filterTag, students, onClose }: Props) {
  const [copied, setCopied] = useState(false);
  const txt = (zh: string, en: string) => lang === 'en' ? en : lang === 'zh_TW' ? toTraditional(zh) : zh;

  const report = useMemo(() => {
    const now = Date.now();
    const weekMs = 7 * 24 * 60 * 60 * 1000;

    let activeThisWeek = 0;
    let totalBattles = 0;
    let totalScore = 0;
    const progressList: { name: string; score: number; progress: number }[] = [];

    for (const s of students) {
      const cm = s.completed_missions as Record<string, any> | null;
      const login = (cm as any)?._login as { lastDate?: string } | undefined;
      const lastDate = login?.lastDate ? new Date(login.lastDate).getTime() : 0;
      if (now - lastDate < weekMs) activeThisWeek++;

      const score = s.total_score || 0;
      totalScore += score;

      // Count completed missions
      const missionKeys = Object.keys(cm || {}).filter(k => !k.startsWith('_'));
      const completed = missionKeys.filter(k => (cm as any)?.[k]?.green).length;

      progressList.push({ name: s.display_name || 'Anonymous', score, progress: completed });
    }

    const sorted = [...progressList].sort((a, b) => b.score - a.score);
    const top3 = sorted.slice(0, 3);
    const bottom3 = sorted.slice(-3).reverse();
    const avgScore = students.length > 0 ? Math.round(totalScore / students.length) : 0;
    const participationRate = students.length > 0 ? Math.round((activeThisWeek / students.length) * 100) : 0;

    const date = new Date().toLocaleDateString(lang === 'en' ? 'en-GB' : 'zh-CN');
    const className = filterTag || `Y${grade}`;

    if (lang === 'en') {
      return `Weekly Report — ${className}
Date: ${date}
━━━━━━━━━━━━━━━━━━━━
Students: ${students.length}
Active this week: ${activeThisWeek} (${participationRate}%)
Average score: ${avgScore}

Top 3 students:
${top3.map((s, i) => `  ${i + 1}. ${s.name} — ${s.score} pts, ${s.progress} missions`).join('\n')}

Need attention:
${bottom3.map(s => `  • ${s.name} — ${s.score} pts, ${s.progress} missions`).join('\n')}

Generated by 25Maths Play · play.25maths.com`;
    }

    const zhReport = `班级周报 — ${className}
日期：${date}
━━━━━━━━━━━━━━━━━━━━
学生人数：${students.length}
本周活跃：${activeThisWeek} 人（${participationRate}%）
班级平均分：${avgScore}

进步最大 Top 3：
${top3.map((s, i) => `  ${i + 1}. ${s.name} — ${s.score} 分，${s.progress} 关`).join('\n')}

需要关注：
${bottom3.map(s => `  · ${s.name} — ${s.score} 分，${s.progress} 关`).join('\n')}

由 25Maths Play 生成 · play.25maths.com`;
    return lang === 'zh_TW' ? toTraditional(zhReport) : zhReport;
  }, [students, grade, filterTag, lang]);

  const handleCopy = () => {
    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-start justify-center bg-black/50 backdrop-blur-sm p-4 pt-8 overflow-y-auto" onClick={onClose}>
      <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full overflow-hidden" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
          <div className="flex items-center gap-2">
            <FileText size={18} className="text-indigo-600" />
            <h2 className="text-base font-black text-slate-800">{txt('班级周报', 'Weekly Report')}</h2>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={handleCopy} className="flex items-center gap-1 px-3 py-1.5 bg-indigo-600 text-white text-xs font-bold rounded-lg hover:bg-indigo-500 transition-colors">
              {copied ? <><Check size={12} /> {txt('已复制！', 'Copied!')}</> : <><Copy size={12} /> {txt('复制', 'Copy')}</>}
            </button>
            <button onClick={onClose} className="text-slate-400 hover:text-slate-600"><X size={18} /></button>
          </div>
        </div>
        <pre className="p-5 text-sm text-slate-700 whitespace-pre-wrap font-mono leading-relaxed max-h-[65vh] overflow-y-auto">
          {report}
        </pre>
      </div>
    </div>
  );
}
