import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { toMissionSummaries } from '../src/utils/missionSummary';
import { MISSIONS_Y7 } from '../src/data/missions/y7';
import { MISSIONS_Y8 } from '../src/data/missions/y8';
import { MISSIONS_Y9 } from '../src/data/missions/y9';
import { MISSIONS_Y10 } from '../src/data/missions/y10';
import { MISSIONS_Y11 } from '../src/data/missions/y11';
import { MISSIONS_Y12 } from '../src/data/missions/y12';

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, 'src/data/missionSummaries');

const FILES = [
  ['y7', 'MISSION_SUMMARIES_Y7', MISSIONS_Y7],
  ['y8', 'MISSION_SUMMARIES_Y8', MISSIONS_Y8],
  ['y9', 'MISSION_SUMMARIES_Y9', MISSIONS_Y9],
  ['y10', 'MISSION_SUMMARIES_Y10', MISSIONS_Y10],
  ['y11', 'MISSION_SUMMARIES_Y11', MISSIONS_Y11],
  ['y12', 'MISSION_SUMMARIES_Y12', MISSIONS_Y12],
] as const;

function renderModule(constName: string, missions: ReturnType<typeof toMissionSummaries>) {
  return `import type { MissionSummary } from '../../types';

// Auto-generated by scripts/generate-mission-summaries.ts
export const ${constName}: MissionSummary[] = ${JSON.stringify(missions, null, 2)} as MissionSummary[];
`;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  for (const [slug, constName, missions] of FILES) {
    const summaries = toMissionSummaries([...missions]);
    const content = renderModule(constName, summaries);
    await writeFile(path.join(OUT_DIR, `${slug}.ts`), content, 'utf8');
  }

  const indexContent = `import type { MissionSummary } from '../../types';
import { MISSION_SUMMARIES_Y7 } from './y7';
import { MISSION_SUMMARIES_Y8 } from './y8';
import { MISSION_SUMMARIES_Y9 } from './y9';
import { MISSION_SUMMARIES_Y10 } from './y10';
import { MISSION_SUMMARIES_Y11 } from './y11';
import { MISSION_SUMMARIES_Y12 } from './y12';

export {
  MISSION_SUMMARIES_Y7,
  MISSION_SUMMARIES_Y8,
  MISSION_SUMMARIES_Y9,
  MISSION_SUMMARIES_Y10,
  MISSION_SUMMARIES_Y11,
  MISSION_SUMMARIES_Y12,
};

export const MISSION_SUMMARIES: MissionSummary[] = [
  ...MISSION_SUMMARIES_Y7,
  ...MISSION_SUMMARIES_Y8,
  ...MISSION_SUMMARIES_Y9,
  ...MISSION_SUMMARIES_Y10,
  ...MISSION_SUMMARIES_Y11,
  ...MISSION_SUMMARIES_Y12,
];
`;
  await writeFile(path.join(OUT_DIR, 'index.ts'), indexContent, 'utf8');
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
